# Check source dependencies, including headers. Fixed cryptography, RS and audio
# are permitted; neither engine may call the other's signal-processing paths.
file(GLOB_RECURSE fast_sources "${ROOT}/src/fast/*.cpp" "${ROOT}/include/datapump/fast/*.hpp")
foreach(path IN LISTS fast_sources)
  file(READ "${path}" source)
  if(source MATCHES "#[ \t]*include[ \t]*[\"<]datapump/(pattern_[^\">]*|recovery|tuning|simulation_estimate|lpi_estimate|streaming_modem|transfer|live|channel|modem)\\.hpp")
    message(FATAL_ERROR "Fast engine imports regular signal processing: ${path}")
  endif()
  if(source MATCHES "Crypto::stream|StreamPurpose::|StreamDomain::")
    message(FATAL_ERROR "Fast engine uses regular epoch streams: ${path}")
  endif()
endforeach()
file(GLOB regular_sources "${ROOT}/src/*.cpp" "${ROOT}/include/datapump/*.hpp")
foreach(path IN LISTS regular_sources)
  get_filename_component(name "${path}" NAME)
  if(name STREQUAL "main.cpp")
    continue()
  endif()
  file(READ "${path}" source)
  if(source MATCHES "#[ \t]*include[ \t]*[\"<]datapump/fast/")
    message(FATAL_ERROR "Regular engine depends on fast mode: ${path}")
  endif()
endforeach()
message(STATUS "Regular/fast DSP dependency boundary passed")
