# Architectural regression: domain IDs and policies belong above the adapters.
# Adding an ordinary feature may extend declarations/controller/presentation,
# but must never introduce another application switch in a toolkit backend.
foreach(name backend_fltk.cpp backend_rev.cpp backend_fltk_document.hpp backend_rev_document.hpp)
  file(READ "${ROOT}/src/gui/${name}" source)
  string(REGEX MATCHALL "(Field|Command|Page|Bitmap|Slot)::[A-Za-z_][A-Za-z_0-9]*" references "${source}")
  foreach(reference IN LISTS references)
    if(NOT reference MATCHES "::(none|count)$")
      message(FATAL_ERROR "${name} contains application binding ${reference}; move that decision into a shared declaration or presentation.")
    endif()
  endforeach()
  if(source MATCHES "#include \"(inspection_model|inspection_page|record_presentations|datapump/(tuning|live|transfer))")
    message(FATAL_ERROR "${name} directly includes application/domain presentation.")
  endif()
  if(source MATCHES "controller\\.(snapshot|settings|inspection|inbox|signals)\\(")
    message(FATAL_ERROR "${name} interprets application data instead of a shared presentation.")
  endif()
endforeach()
foreach(name GuiFltk.cmake GuiRev.cmake)
  file(READ "${ROOT}/cmake/${name}" source)
  if(source MATCHES "src/gui/(main|controller|screen_console|inspection_widgets|gui_smoke)\\.cpp")
    message(FATAL_ERROR "${name} owns shared application source lists; link datapump_gui_application instead.")
  endif()
endforeach()
foreach(name main.cpp live_widgets.hpp inspection_widgets.cpp inspection_widgets.hpp pattern_space_view.hpp screen_inspection.cpp backend_rev_inspection.hpp)
  if(EXISTS "${ROOT}/src/gui/${name}")
    message(FATAL_ERROR "Obsolete parallel GUI implementation remains: ${name}")
  endif()
endforeach()
