cmake_minimum_required(VERSION 3.21)
# Prove the architecture guard follows helper dependencies and discovers new
# adapter files, rather than only rejecting names in the current entry points.
file(REMOVE_RECURSE "${BINARY_DIR}/gui-boundary-fixture")
set(fixture "${BINARY_DIR}/gui-boundary-fixture")
file(MAKE_DIRECTORY "${fixture}/src" "${fixture}/cmake")
file(COPY "${ROOT}/src/gui" DESTINATION "${fixture}/src")
file(COPY "${ROOT}/cmake/GuiFltk.cmake" "${ROOT}/cmake/GuiRev.cmake" DESTINATION "${fixture}/cmake")

function(check_guard should_pass expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT=${fixture}" -P "${ROOT}/tests/gui_adapter_boundary.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(should_pass AND NOT result EQUAL 0)
    message(FATAL_ERROR "Clean GUI boundary fixture failed: ${output}${error}")
  elseif(NOT should_pass AND (result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}"))
    message(FATAL_ERROR "GUI boundary escape was not detected: ${output}${error}")
  endif()
endfunction()

check_guard(TRUE "")
file(READ "${fixture}/src/gui/theme.hpp" clean_theme)
file(APPEND "${fixture}/src/gui/theme.hpp" "\n#include <controller.hpp>\n")
check_guard(FALSE "controller.hpp.*outside the public")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "auto command = ui::Command::transmit;\n")
check_guard(FALSE "application binding Command::transmit")
file(REMOVE "${fixture}/src/gui/backend_extra.cpp")

# Allowed public helpers are generic vocabulary, not an escape hatch for native
# code to hide feature decisions behind an otherwise permitted include.
file(APPEND "${fixture}/src/gui/theme.hpp" "\ninline auto hidden_command() { return ui::Command::transmit; }\n")
check_guard(FALSE "theme.hpp contains application binding Command::transmit")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")
file(READ "${fixture}/src/gui/control_layout.hpp" clean_layout)
file(APPEND "${fixture}/src/gui/control_layout.hpp" "\ninline auto hidden_field() { return ui::Field::message; }\n")
check_guard(FALSE "control_layout.hpp contains application binding Field::message")
file(WRITE "${fixture}/src/gui/control_layout.hpp" "${clean_layout}")

# Formatting and local type aliases must preserve the same boundary. None/count
# remain legal sentinels, including when the public types are abbreviated.
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "using Action = ui::Command; using Another = Action; auto command = Another :: none;\n")
check_guard(TRUE "")
file(APPEND "${fixture}/src/gui/backend_extra.cpp" "auto hidden = Another :: transmit;\n")
check_guard(FALSE "application binding Another::transmit")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "typedef ui::Field Binding; auto hidden = Binding :: message;\n")
check_guard(FALSE "application binding Binding::message")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "auto hidden = ui::Command \n :: \n transmit;\n")
check_guard(FALSE "application binding Command::transmit")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "auto hidden = ui::Menu::keyfile;\n")
check_guard(FALSE "application binding Menu::keyfile")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "using enum ui::Command; auto hidden = transmit;\n")
check_guard(FALSE "imports application bindings with using enum")
file(REMOVE "${fixture}/src/gui/backend_extra.cpp")

# Aliases declared by an included helper must remain opaque in every adapter,
# including chains whose aliases occur in a different traversal order.
file(APPEND "${fixture}/src/gui/theme.hpp" "\nusing PublicBinding = ui::Command;\n")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "#include \"theme.hpp\"\nusing LocalBinding = PublicBinding; auto allowed = LocalBinding::none;\n")
check_guard(TRUE "")
file(APPEND "${fixture}/src/gui/backend_extra.cpp" "auto hidden = LocalBinding::transmit;\n")
check_guard(FALSE "application binding LocalBinding::transmit")
file(REMOVE "${fixture}/src/gui/backend_extra.cpp")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")

# Standard preprocessing whitespace and comments cannot hide a dependency or a
# binding. Comment-looking text inside strings must not swallow following code.
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "// ui::Command::transmit is forbidden in code.\n/* #include <controller.hpp> */\nauto legal = ui::Command /* sentinel */ :: none;\n")
check_guard(TRUE "")
file(APPEND "${fixture}/src/gui/backend_extra.cpp" "const char* diagnostic = \"Command::transmit\"; auto unrelated = NativeCommand::value;\n")
check_guard(TRUE "")
file(APPEND "${fixture}/src/gui/backend_extra.cpp" "const char* url = \"https://example.invalid/*text*/\"; auto hidden = ui::Command /* gap */ :: transmit;\n")
check_guard(FALSE "application binding Command::transmit")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "# /* comment */ include <controller.hpp>\n")
check_guard(FALSE "controller.hpp.*outside the public")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "#inc\\\nlude <controller.hpp>\n")
check_guard(FALSE "controller.hpp.*outside the public")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "#define PRIVATE_HEADER <controller.hpp>\n#include PRIVATE_HEADER\n")
check_guard(FALSE "nonliteral include")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "#include_next <controller.hpp>\n")
check_guard(FALSE "unsupported include directive")
file(WRITE "${fixture}/src/gui/backend_extra.cpp" "#include <unexpected/controller.hpp>\n")
check_guard(FALSE "unexpected/controller.hpp.*outside the public")
file(REMOVE "${fixture}/src/gui/backend_extra.cpp")

# New suffixes or nested folders cannot create an unexamined feature/backend.
foreach(extension cc cxx h inc inl cppm)
  file(MAKE_DIRECTORY "${fixture}/src/gui/nested")
  file(WRITE "${fixture}/src/gui/nested/backend_extra.${extension}" "auto hidden = ui::Field::message;\n")
  check_guard(FALSE "application binding Field::message")
  file(REMOVE "${fixture}/src/gui/nested/backend_extra.${extension}")
  file(WRITE "${fixture}/src/gui/nested/feature.${extension}" "#include <FL/Fl.H>\n")
  check_guard(FALSE "depends on a native adapter/toolkit")
  file(REMOVE "${fixture}/src/gui/nested/feature.${extension}")
endforeach()

file(APPEND "${fixture}/src/gui/application.hpp" "\n#include <FL/Fl.H>\n")
check_guard(FALSE "depends on a native toolkit")
file(COPY "${ROOT}/src/gui/application.hpp" DESTINATION "${fixture}/src/gui")
file(APPEND "${fixture}/src/gui/theme.hpp" "\n#include <third_party/rev/source/private.hpp>\n")
check_guard(FALSE "depends on a native toolkit")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")
file(APPEND "${fixture}/src/gui/theme.hpp" "\n#include <unexpected/controller.hpp>\n")
check_guard(FALSE "unexpected/controller.hpp.*outside the public")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")
file(APPEND "${fixture}/src/gui/theme.hpp" "\nimport Rev.Element;\n")
check_guard(FALSE "unsupported module import")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")
file(APPEND "${fixture}/src/gui/theme.hpp" "\nimport <FL/Fl.H>;\n")
check_guard(FALSE "depends on a native toolkit")
file(WRITE "${fixture}/src/gui/theme.hpp" "${clean_theme}")

file(READ "${fixture}/src/gui/screen_console.cpp" clean_screen)
file(APPEND "${fixture}/src/gui/screen_console.cpp" "\n#include <FL/Fl.H>\n")
check_guard(FALSE "depends on a native adapter/toolkit")
file(WRITE "${fixture}/src/gui/screen_console.cpp" "${clean_screen}")
file(APPEND "${fixture}/src/gui/screen_console.cpp" "\n#inc\\\nlude <FL/Fl.H>\n")
check_guard(FALSE "depends on a native adapter/toolkit")
file(WRITE "${fixture}/src/gui/screen_console.cpp" "${clean_screen}")
file(APPEND "${fixture}/src/gui/screen_console.cpp" "\n#define NATIVE_HEADER <FL/Fl.H>\n#include NATIVE_HEADER\n")
check_guard(FALSE "nonliteral include")
file(WRITE "${fixture}/src/gui/screen_console.cpp" "${clean_screen}")
file(APPEND "${fixture}/src/gui/screen_console.cpp" "\nRev :: Element::Element* leaked;\n")
check_guard(FALSE "depends on a native adapter/toolkit")
file(WRITE "${fixture}/src/gui/screen_console.cpp" "${clean_screen}")
file(APPEND "${fixture}/src/gui/screen_console.cpp" "\n#if defined(DATAPUMP_GUI_BACKEND_REV)\nint duplicate_feature;\n#endif\n")
check_guard(FALSE "branches on a native backend")
file(WRITE "${fixture}/src/gui/screen_console.cpp" "${clean_screen}")

# Adding a shared source later must not require extending a blacklist of the
# application's filenames to keep it out of each native build recipe.
foreach(profile GuiFltk.cmake GuiRev.cmake)
  file(READ "${fixture}/cmake/${profile}" clean_profile)
  file(APPEND "${fixture}/cmake/${profile}" "\ntarget_sources(datapump-gui PRIVATE src/gui/new_feature.cpp)\n")
  check_guard(FALSE "duplicates shared application source src/gui/new_feature.cpp")
  file(WRITE "${fixture}/cmake/${profile}" "${clean_profile}")
endforeach()
check_guard(TRUE "")
file(REMOVE_RECURSE "${fixture}")
