cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../tools/gui-smoke-timeout.cmake")
set(gui_smoke_options "")
if(DEFINED GUI_SMOKE_TIMEOUT)
  list(APPEND gui_smoke_options "-DGUI_SMOKE_TIMEOUT=${GUI_SMOKE_TIMEOUT}")
endif()
if(NOT DEFINED BUILD_DIR)
  message(FATAL_ERROR "Provide -DBUILD_DIR=/path/to/native/build")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
if(NOT DEFINED CONFIG)
  set(CONFIG Release)
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identifier)
set(scratch "${BUILD_DIR}/package-tests/${identifier}")
set(original "${scratch}/original installation")
set(relocated "${scratch}/offline destination/Data Pump with spaces")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config "${CONFIG}" --prefix "${original}"
  RESULT_VARIABLE installed OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT installed EQUAL 0)
  message(FATAL_ERROR "Native installation failed:\n${output}\n${error}")
endif()
file(MAKE_DIRECTORY "${relocated}")
file(COPY "${original}/" DESTINATION "${relocated}")
file(RENAME "${original}" "${scratch}/unavailable original")
set(manuals pump pump-fast)
if(EXISTS "${relocated}/bin/datapump-gui" OR EXISTS "${relocated}/bin/datapump-gui.exe")
  list(APPEND manuals datapump-gui)
endif()
foreach(manual IN LISTS manuals)
  set(installed_manual "${relocated}/share/man/man1/${manual}.1")
  if(NOT EXISTS "${installed_manual}")
    message(FATAL_ERROR "Native installation omitted the ${manual}(1) manual")
  endif()
  file(SHA256 "${installed_manual}" installed_hash)
  file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../docs/man/${manual}.1" source_hash)
  if(NOT installed_hash STREQUAL source_hash)
    message(FATAL_ERROR "Installed ${manual}(1) differs from its source")
  endif()
endforeach()
set(verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-native-package.cmake")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" "-DBUILD_DIR=${BUILD_DIR}"
  "-DGUI_SMOKE=${GUI_SMOKE}" -DREQUIRE_MANUALS=ON ${gui_smoke_options} -P "${verifier}"
  RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT verified EQUAL 0)
  message(FATAL_ERROR "Native relocation failed:\n${output}\n${error}")
endif()
# Tampering and unlisted additions must be distinguished from a verified copy.
set(victim "${relocated}/bin/pump${CMAKE_EXECUTABLE_SUFFIX}")
if(WIN32)
  set(victim "${relocated}/bin/pump.exe")
endif()
file(COPY_FILE "${victim}" "${scratch}/original-pump")
file(APPEND "${victim}" "tampered")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE tampering OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(tampering EQUAL 0 OR NOT error MATCHES "Modified package file")
  message(FATAL_ERROR "Native package verification failed to reject modified content")
endif()
file(COPY_FILE "${scratch}/original-pump" "${victim}")
# A self-consistent inventory is insufficient when a required manual is absent.
set(manual "${relocated}/share/man/man1/pump.1")
file(READ "${relocated}/manifest.sha256" complete_manifest)
file(RENAME "${manual}" "${scratch}/original-pump.1")
string(REGEX REPLACE "[0-9a-f]+  share/man/man1/pump\\.1\n" "" missing_manual_manifest "${complete_manifest}")
file(WRITE "${relocated}/manifest.sha256" "${missing_manual_manifest}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE missing_manual OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(missing_manual EQUAL 0 OR NOT error MATCHES "lacks the pump")
  message(FATAL_ERROR "Native package verification accepted a missing manual")
endif()
file(RENAME "${scratch}/original-pump.1" "${manual}")
file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
# Current helpers can still certify the inventory of historical releases, but
# newly produced archives must opt into the complete manual requirement.
foreach(manual IN LISTS manuals)
  file(RENAME "${relocated}/share/man/man1/${manual}.1" "${scratch}/${manual}.1")
endforeach()
string(REGEX REPLACE "[0-9a-f]+  share/man/man1/[^\n]+\n" "" historical_manifest "${complete_manifest}")
file(WRITE "${relocated}/manifest.sha256" "${historical_manifest}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE historical OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT historical EQUAL 0 OR NOT output MATCHES "Historical native package")
  message(FATAL_ERROR "Historical package without manuals failed inventory verification: ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -DREQUIRE_MANUALS=ON -P "${verifier}"
  RESULT_VARIABLE missing_manuals OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(missing_manuals EQUAL 0 OR NOT error MATCHES "lacks the pump")
  message(FATAL_ERROR "New package verification accepted an absent manual set")
endif()
foreach(manual IN LISTS manuals)
  file(RENAME "${scratch}/${manual}.1" "${relocated}/share/man/man1/${manual}.1")
endforeach()
file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
file(WRITE "${relocated}/unexpected-file.txt" "not part of the installation")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE extra OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(extra EQUAL 0 OR NOT error MATCHES "unrecorded")
  message(FATAL_ERROR "Native package verification failed to reject an unrecorded file")
endif()
message(STATUS "Native relocation and package corruption checks passed: ${relocated}")
