cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED BINARY_DIR)
  message(FATAL_ERROR "Provide -DBINARY_DIR for the packaging fixture build")
endif()

set(source "${CMAKE_CURRENT_LIST_DIR}/packaging_fixture")
set(compiler_options "")
if(CXX_COMPILER)
  # Reuse the selected compiler without selecting the application's SDK
  # packaging policy: this fixture exercises native shared-library collection.
  list(APPEND compiler_options "-DCMAKE_CXX_COMPILER:FILEPATH=${CXX_COMPILER}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${BINARY_DIR}" -DCMAKE_BUILD_TYPE=Release
  ${compiler_options}
  RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT configured EQUAL 0)
  message(FATAL_ERROR "Packaging fixture configure failed:\n${output}\n${error}")
endif()
if(CXX_COMPILER)
  load_cache("${BINARY_DIR}" READ_WITH_PREFIX fixture_ CMAKE_CXX_COMPILER)
  file(REAL_PATH "${CXX_COMPILER}" requested_compiler)
  file(REAL_PATH "${fixture_CMAKE_CXX_COMPILER}" configured_compiler)
  if(NOT configured_compiler STREQUAL requested_compiler)
    message(FATAL_ERROR "Packaging fixture used '${fixture_CMAKE_CXX_COMPILER}' instead of '${CXX_COMPILER}'")
  endif()
  message(STATUS "Packaging fixture C++ compiler: ${fixture_CMAKE_CXX_COMPILER}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config Release --parallel 2
  RESULT_VARIABLE built OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT built EQUAL 0)
  message(FATAL_ERROR "Packaging fixture build failed:\n${output}\n${error}")
endif()
set(BUILD_DIR "${BINARY_DIR}")
set(CONFIG Release)
set(GUI_SMOKE OFF)
include("${CMAKE_CURRENT_LIST_DIR}/package_native.cmake")

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  set(alsa_soname "${relocated}/lib/libasound.so.2")
  if(NOT EXISTS "${alsa_soname}" OR IS_SYMLINK "${alsa_soname}")
    message(FATAL_ERROR "Packaged audio must include an owned libasound.so.2 file")
  endif()
  file(SHA256 "${alsa_soname}" alsa_hash)
  file(SHA256 "${relocated}/lib/libasound.so.2.0.0" versioned_hash)
  if(NOT alsa_hash STREQUAL versioned_hash)
    message(FATAL_ERROR "Packaged ALSA SONAME differs from its selected library")
  endif()
  set(abi_fixture "${scratch}/abi fixture")
  file(MAKE_DIRECTORY "${abi_fixture}/bin" "${abi_fixture}/lib")
  file(COPY_FILE "${relocated}/bin/pump" "${abi_fixture}/bin/pump")
  set(abi_verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-linux-abi.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -DMAX_GLIBC=999.0 -P "${abi_verifier}"
    RESULT_VARIABLE accepted OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT accepted EQUAL 0)
    message(FATAL_ERROR "ELF ABI audit rejected a native fixture: ${output}\n${error}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -DMAX_GLIBC=2.0 -P "${abi_verifier}"
    RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(rejected EQUAL 0 OR NOT error MATCHES "requires glibc")
    message(FATAL_ERROR "ELF ABI audit failed to reject a newer glibc requirement")
  endif()
  file(COPY_FILE "${abi_fixture}/bin/pump" "${abi_fixture}/lib/libglib-2.0.so.0")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -P "${abi_verifier}"
    RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(rejected EQUAL 0 OR NOT error MATCHES "includes GTK/GLib")
    message(FATAL_ERROR "ELF ABI audit failed to reject an accidental GLib dependency")
  endif()
endif()

# Exercise the artifact verifier with both archive formats, including the
# downstream checksum check before any copied executable can be launched.
set(archive_source "${scratch}/archive source")
set(archive_directory "${scratch}/archives")
file(MAKE_DIRECTORY "${archive_source}/DataPump-fixture-native" "${archive_directory}")
file(COPY "${relocated}/" DESTINATION "${archive_source}/DataPump-fixture-native")
file(REMOVE "${archive_source}/DataPump-fixture-native/unexpected-file.txt")
foreach(format TGZ ZIP)
  if(format STREQUAL "TGZ")
    set(archive "${archive_directory}/DataPump-fixture-native.tar.gz")
    set(archive_arguments cfz "${archive}")
  else()
    set(archive "${archive_directory}/DataPump-fixture-native.zip")
    set(archive_arguments cf "${archive}" --format=zip)
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar ${archive_arguments} DataPump-fixture-native
    WORKING_DIRECTORY "${archive_source}" RESULT_VARIABLE archived)
  if(NOT archived EQUAL 0)
    message(FATAL_ERROR "Could not create packaging test archive")
  endif()
endforeach()
set(archive_verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-native-archives.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/package_gui_smoke_timeout.cmake")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${archive_directory}" "-DBUILD_DIR=${BINARY_DIR}"
  -P "${archive_verifier}" RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT verified EQUAL 0 OR NOT EXISTS "${archive_directory}/SHA256SUMS.txt")
  message(FATAL_ERROR "Native archive fixture failed verification: ${output}\n${error}")
endif()
file(APPEND "${archive_directory}/DataPump-fixture-native.zip" "changed in transit")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${archive_directory}" "-DBUILD_DIR=${BINARY_DIR}"
  -P "${archive_verifier}" RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(rejected EQUAL 0 OR NOT error MATCHES "checksums differ")
  message(FATAL_ERROR "Native archive verifier failed to reject a changed download")
endif()

# GUI backends use distinct roots so both releases can share one download
# directory. Keep the unsuffixed CLI fixture above and verify each GUI pair.
foreach(backend fltk rev)
  set(basename "DataPump-fixture-native-${backend}")
  set(backend_archives "${scratch}/${backend} archives")
  file(MAKE_DIRECTORY "${archive_source}/${basename}" "${backend_archives}")
  file(COPY "${relocated}/" DESTINATION "${archive_source}/${basename}")
  file(REMOVE "${archive_source}/${basename}/unexpected-file.txt")
  foreach(format TGZ ZIP)
    if(format STREQUAL "TGZ")
      set(archive_arguments cfz "${backend_archives}/${basename}.tar.gz")
    else()
      set(archive_arguments cf "${backend_archives}/${basename}.zip" --format=zip)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar ${archive_arguments} "${basename}"
      WORKING_DIRECTORY "${archive_source}" RESULT_VARIABLE archived)
    if(NOT archived EQUAL 0)
      message(FATAL_ERROR "Could not create ${backend} packaging test archive")
    endif()
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${backend_archives}" "-DBUILD_DIR=${BINARY_DIR}"
    -P "${archive_verifier}" RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT verified EQUAL 0 OR NOT EXISTS "${backend_archives}/SHA256SUMS.txt")
    message(FATAL_ERROR "${backend} archive fixture failed verification: ${output}\n${error}")
  endif()
  file(REMOVE "${backend_archives}/${basename}.zip" "${backend_archives}/SHA256SUMS.txt")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${backend_archives}" -P "${archive_verifier}"
    RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(rejected EQUAL 0 OR NOT error MATCHES "Both native TGZ and ZIP archives must be present")
    message(FATAL_ERROR "${backend} archive verifier accepted an incomplete pair")
  endif()
endforeach()
