# Exercise the real verifier with the tiny packaging executables. Expanded CMake
# traces expose the process deadline without making a fixture sleep for minutes.
function(check_gui_smoke_timeouts package_directory archive_directory fixture_build)
  set(package_verifier "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/verify-native-package.cmake")
  set(archive_verifier "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/verify-native-archives.cmake")
  file(REAL_PATH "${package_verifier}" package_verifier)
  file(REAL_PATH "${archive_verifier}" archive_verifier)
  foreach(verifier IN ITEMS "${package_verifier}" "${archive_verifier}")
    foreach(invalid IN ITEMS "" 9 601 -1 1.5 30s)
      execute_process(COMMAND "${CMAKE_COMMAND}" "-DGUI_SMOKE_TIMEOUT=${invalid}" -P "${verifier}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
      if(status EQUAL 0 OR NOT error MATCHES "GUI_SMOKE_TIMEOUT must be an integer from 10 to 600")
        message(FATAL_ERROR "Verifier did not reject GUI timeout '${invalid}': ${output}\n${error}")
      endif()
    endforeach()
  endforeach()

  foreach(allowance IN ITEMS default 10 300 600)
    set(options "")
    set(expected_process_timeout 120)
    if(NOT allowance STREQUAL "default")
      list(APPEND options "-DGUI_SMOKE_TIMEOUT=${allowance}")
      math(EXPR expected_process_timeout "${allowance} + 30")
    endif()
    set(trace "${fixture_build}/gui-timeout-${allowance}.jsonl")
    execute_process(COMMAND "${CMAKE_COMMAND}" --trace-expand --trace-format=json-v1
      "--trace-source=${package_verifier}" "--trace-redirect=${trace}"
      "-DPACKAGE_ROOT=${package_directory}" "-DBUILD_DIR=${fixture_build}"
      -DGUI_SMOKE=ON ${options} -P "${package_verifier}"
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "GUI timeout fixture '${allowance}' failed: ${output}\n${error}")
    endif()
    file(STRINGS "${trace}" lines)
    set(smoke_commands 0)
    set(other_commands 0)
    foreach(line IN LISTS lines)
      string(JSON command ERROR_VARIABLE ignored GET "${line}" cmd)
      if(NOT command STREQUAL "execute_process")
        continue()
      endif()
      string(JSON count LENGTH "${line}" args)
      math(EXPR last "${count} - 1")
      set(arguments "")
      foreach(index RANGE 0 ${last})
        string(JSON argument GET "${line}" args ${index})
        list(APPEND arguments "${argument}")
      endforeach()
      list(FIND arguments TIMEOUT timeout_index)
      math(EXPR timeout_index "${timeout_index} + 1")
      list(GET arguments ${timeout_index} actual_timeout)
      list(FIND arguments --smoke-test smoke_index)
      list(FIND arguments --smoke-timeout allowance_index)
      if(NOT smoke_index EQUAL -1)
        math(EXPR smoke_commands "${smoke_commands} + 1")
        if(NOT actual_timeout EQUAL expected_process_timeout)
          message(FATAL_ERROR "GUI process timeout '${actual_timeout}' differs from '${expected_process_timeout}'")
        endif()
        if(allowance STREQUAL "default")
          if(NOT allowance_index EQUAL -1)
            message(FATAL_ERROR "Default GUI invocation gained an explicit timeout")
          endif()
        else()
          if(allowance_index EQUAL -1)
            message(FATAL_ERROR "Explicit GUI workflow timeout was not passed to the executable")
          endif()
          math(EXPR allowance_index "${allowance_index} + 1")
          list(GET arguments ${allowance_index} actual_allowance)
          if(NOT actual_allowance STREQUAL allowance)
            message(FATAL_ERROR "GUI received '${actual_allowance}', expected '${allowance}'")
          endif()
        endif()
      else()
        math(EXPR other_commands "${other_commands} + 1")
        if(NOT actual_timeout EQUAL 120 OR NOT allowance_index EQUAL -1)
          message(FATAL_ERROR "GUI timeout changed a CLI/self-check invocation")
        endif()
      endif()
    endforeach()
    if(NOT smoke_commands EQUAL 1 OR NOT other_commands EQUAL 4)
      message(FATAL_ERROR "Expected one GUI workflow plus version, two simulations, and GUI self-check")
    endif()
  endforeach()

  set(trace "${fixture_build}/gui-timeout-archives.jsonl")
  execute_process(COMMAND "${CMAKE_COMMAND}" --trace-expand --trace-format=json-v1
    "--trace-source=${archive_verifier}" "--trace-redirect=${trace}"
    "-DARCHIVE_DIR=${archive_directory}" "-DBUILD_DIR=${fixture_build}"
    -DGUI_SMOKE=ON -DGUI_SMOKE_TIMEOUT=300 -P "${archive_verifier}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Archive GUI timeout fixture failed: ${output}\n${error}")
  endif()
  file(STRINGS "${trace}" lines)
  set(forwarded 0)
  foreach(line IN LISTS lines)
    string(JSON command ERROR_VARIABLE ignored GET "${line}" cmd)
    if(command STREQUAL "execute_process" AND line MATCHES "verify-native-package\\.cmake")
      if(NOT line MATCHES "-DGUI_SMOKE_TIMEOUT=300" OR NOT line MATCHES "-DGUI_SMOKE=ON")
        message(FATAL_ERROR "Archive verification did not forward the requested GUI workflow allowance")
      endif()
      math(EXPR forwarded "${forwarded} + 1")
    endif()
  endforeach()
  if(NOT forwarded EQUAL 2)
    message(FATAL_ERROR "GUI timeout was not checked for both archive formats")
  endif()
  message(STATUS "GUI smoke timeout defaults, bounds, process deadlines, and archive forwarding verified")
endfunction()

check_gui_smoke_timeouts("${archive_source}/DataPump-fixture-native" "${archive_directory}" "${BINARY_DIR}")
