cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED BINARY_DIR)
  message(FATAL_ERROR "Provide -DBINARY_DIR for the packaging fixture build")
endif()
set(source "${CMAKE_CURRENT_LIST_DIR}/packaging_fixture")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${BINARY_DIR}" -DCMAKE_BUILD_TYPE=Release
  RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT configured EQUAL 0)
  message(FATAL_ERROR "Packaging fixture configure failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config Release --parallel 2
  RESULT_VARIABLE built OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT built EQUAL 0)
  message(FATAL_ERROR "Packaging fixture build failed:\n${output}\n${error}")
endif()
set(BUILD_DIR "${BINARY_DIR}")
set(CONFIG Release)
set(GUI_SMOKE OFF)
include("${CMAKE_CURRENT_LIST_DIR}/package_native.cmake")
