cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED BINARY_DIR)
  message(FATAL_ERROR "Provide -DBINARY_DIR for the packaging fixture build")
endif()

set(source "${CMAKE_CURRENT_LIST_DIR}/packaging_fixture")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${BINARY_DIR}" -DCMAKE_BUILD_TYPE=Release
  RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT configured EQUAL 0)
  message(FATAL_ERROR "Packaging fixture configure failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config Release --parallel 2
  RESULT_VARIABLE built OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT built EQUAL 0)
  message(FATAL_ERROR "Packaging fixture build failed:\n${output}\n${error}")
endif()
set(BUILD_DIR "${BINARY_DIR}")
set(CONFIG Release)
set(GUI_SMOKE OFF)
include("${CMAKE_CURRENT_LIST_DIR}/package_native.cmake")

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  set(abi_fixture "${scratch}/abi fixture")
  file(MAKE_DIRECTORY "${abi_fixture}/bin" "${abi_fixture}/lib")
  file(COPY_FILE "${relocated}/bin/pump" "${abi_fixture}/bin/pump")
  set(abi_verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-linux-abi.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -DMAX_GLIBC=999.0 -P "${abi_verifier}"
    RESULT_VARIABLE accepted OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT accepted EQUAL 0)
    message(FATAL_ERROR "ELF ABI audit rejected a native fixture: ${output}\n${error}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -DMAX_GLIBC=2.0 -P "${abi_verifier}"
    RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(rejected EQUAL 0 OR NOT error MATCHES "requires glibc")
    message(FATAL_ERROR "ELF ABI audit failed to reject a newer glibc requirement")
  endif()
  file(COPY_FILE "${abi_fixture}/bin/pump" "${abi_fixture}/lib/libglib-2.0.so.0")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${abi_fixture}" -P "${abi_verifier}"
    RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(rejected EQUAL 0 OR NOT error MATCHES "includes GTK/GLib")
    message(FATAL_ERROR "ELF ABI audit failed to reject an accidental GLib dependency")
  endif()
endif()

# Exercise the artifact verifier with both archive formats, including the
# downstream checksum check before any copied executable can be launched.
set(archive_source "${scratch}/archive source")
set(archive_directory "${scratch}/archives")
file(MAKE_DIRECTORY "${archive_source}/DataPump-fixture-native" "${archive_directory}")
file(COPY "${relocated}/" DESTINATION "${archive_source}/DataPump-fixture-native")
file(REMOVE "${archive_source}/DataPump-fixture-native/unexpected-file.txt")
foreach(format TGZ ZIP)
  if(format STREQUAL "TGZ")
    set(archive "${archive_directory}/DataPump-fixture-native.tar.gz")
    set(archive_arguments cfz "${archive}")
  else()
    set(archive "${archive_directory}/DataPump-fixture-native.zip")
    set(archive_arguments cf "${archive}" --format=zip)
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar ${archive_arguments} DataPump-fixture-native
    WORKING_DIRECTORY "${archive_source}" RESULT_VARIABLE archived)
  if(NOT archived EQUAL 0)
    message(FATAL_ERROR "Could not create packaging test archive")
  endif()
endforeach()
set(archive_verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-native-archives.cmake")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${archive_directory}" "-DBUILD_DIR=${BINARY_DIR}"
  -P "${archive_verifier}" RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT verified EQUAL 0 OR NOT EXISTS "${archive_directory}/SHA256SUMS.txt")
  message(FATAL_ERROR "Native archive fixture failed verification: ${output}\n${error}")
endif()
file(APPEND "${archive_directory}/DataPump-fixture-native.zip" "changed in transit")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE_DIR=${archive_directory}" "-DBUILD_DIR=${BINARY_DIR}"
  -P "${archive_verifier}" RESULT_VARIABLE rejected OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(rejected EQUAL 0 OR NOT error MATCHES "checksums differ")
  message(FATAL_ERROR "Native archive verifier failed to reject a changed download")
endif()
