cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../tools/gui-smoke-timeout.cmake")
set(gui_smoke_options "")
if(DEFINED GUI_SMOKE_TIMEOUT)
  list(APPEND gui_smoke_options "-DGUI_SMOKE_TIMEOUT=${GUI_SMOKE_TIMEOUT}")
endif()
if(NOT DEFINED BUILD_DIR)
  message(FATAL_ERROR "Provide -DBUILD_DIR=/path/to/native/build")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
if(NOT DEFINED CONFIG)
  set(CONFIG Release)
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identifier)
set(scratch "${BUILD_DIR}/package-tests/${identifier}")
set(original "${scratch}/original installation")
set(relocated "${scratch}/offline destination/Data Pump with spaces")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config "${CONFIG}" --prefix "${original}"
  RESULT_VARIABLE installed OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT installed EQUAL 0)
  message(FATAL_ERROR "Native installation failed:\n${output}\n${error}")
endif()
file(MAKE_DIRECTORY "${relocated}")
file(COPY "${original}/" DESTINATION "${relocated}")
file(RENAME "${original}" "${scratch}/unavailable original")
set(verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-native-package.cmake")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" "-DBUILD_DIR=${BUILD_DIR}"
  "-DGUI_SMOKE=${GUI_SMOKE}" ${gui_smoke_options} -P "${verifier}"
  RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT verified EQUAL 0)
  message(FATAL_ERROR "Native relocation failed:\n${output}\n${error}")
endif()
# Tampering and unlisted additions must be distinguished from a verified copy.
set(victim "${relocated}/bin/pump${CMAKE_EXECUTABLE_SUFFIX}")
if(WIN32)
  set(victim "${relocated}/bin/pump.exe")
endif()
file(COPY_FILE "${victim}" "${scratch}/original-pump")
file(APPEND "${victim}" "tampered")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE tampering OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(tampering EQUAL 0 OR NOT error MATCHES "Modified package file")
  message(FATAL_ERROR "Native package verification failed to reject modified content")
endif()
file(COPY_FILE "${scratch}/original-pump" "${victim}")
file(WRITE "${relocated}/unexpected-file.txt" "not part of the installation")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE extra OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(extra EQUAL 0 OR NOT error MATCHES "unrecorded")
  message(FATAL_ERROR "Native package verification failed to reject an unrecorded file")
endif()
message(STATUS "Native relocation and package corruption checks passed: ${relocated}")
