cmake_minimum_required(VERSION 3.21)
if(NOT BINARY_DIR OR NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "Provide -DBINARY_DIR for the Linux C++ runtime fixture")
endif()
set(source "${CMAKE_CURRENT_LIST_DIR}/packaging_cxx_runtime")
set(compiler_options "")
if(CXX_COMPILER)
  list(APPEND compiler_options "-DCMAKE_CXX_COMPILER:FILEPATH=${CXX_COMPILER}")
endif()
function(checked description)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${description}:\n${output}\n${error}")
  endif()
  set(last_output "${output}${error}" PARENT_SCOPE)
endfunction()
find_program(readelf NAMES readelf REQUIRED)
foreach(mode before after)
  set(build "${BINARY_DIR}/${mode}")
  set(apply OFF)
  if(mode STREQUAL "after")
    set(apply ON)
  endif()
  checked("Configure ${mode}" "${CMAKE_COMMAND}" -S "${source}" -B "${build}"
    -DCMAKE_BUILD_TYPE=Release "-DAPPLY_RUNTIME_POLICY=${apply}" ${compiler_options})
  load_cache("${build}" READ_WITH_PREFIX fixture_ CMAKE_CXX_COMPILER)
  file(READ "${build}/policy.txt" policy)
  if(NOT policy MATCHES "enabled=1|enabled=ON|enabled=TRUE")
    message(FATAL_ERROR "The selected compiler must use the portable GNU C++ runtime: ${policy}")
  endif()
  checked("Build ${mode}" "${CMAKE_COMMAND}" --build "${build}" --parallel 2)
  set(stage "${build}/stage")
  set(relocated "${build}/offline destination with spaces")
  file(REMOVE_RECURSE "${stage}" "${relocated}")
  checked("Install ${mode}" "${CMAKE_COMMAND}" --install "${build}" --prefix "${stage}")
  file(RENAME "${stage}" "${relocated}")
  set(executable "${relocated}/bin/runtime_probe")
  checked("ELF dependencies ${mode}" "${readelf}" --dynamic "${executable}")
  set(dynamic "${last_output}")
  if(NOT dynamic MATCHES "\\(RPATH\\).*\\$ORIGIN/../lib")
    message(FATAL_ERROR "The runtime regression must use the production inherited RPATH")
  endif()
  file(GLOB cxx_runtime "${relocated}/lib/libstdc++*" "${relocated}/lib/libgcc_s*")
  if(mode STREQUAL "before")
    # Establish that this fixture reaches the original failure mechanism:
    # the executable needs and packages a runtime inherited by host plugins.
    if(NOT dynamic MATCHES "NEEDED.*libstdc\\+\\+" OR NOT cxx_runtime)
      message(FATAL_ERROR "The baseline no longer reproduces the bundled C++ runtime")
    endif()
    message(STATUS "Baseline reproduced: inherited RPATH selects bundled libstdc++")
  else()
    if(dynamic MATCHES "NEEDED.*(libstdc\\+\\+|libgcc_s)" OR cxx_runtime)
      message(FATAL_ERROR "Portable application still depends on/bundles a dynamic C++ runtime")
    endif()
    checked("Relocated host plugin isolation" "${executable}" "${build}/libhost_plugin.so")
    if(NOT last_output MATCHES "plugin C\\+\\+ runtime: .*libstdc\\+\\+\\.so")
      message(FATAL_ERROR "Host plugin did not identify its separate C++ runtime: ${last_output}")
    endif()
    message(STATUS "${last_output}")
    checked("Retained ELF ABI audit" "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}"
      -P "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-linux-abi.cmake")
    file(READ "${build}/package-native-configured.cmake" package_script)
    foreach(archive libstdc++.a libgcc.a libgcc_eh.a)
      string(FIND "${package_script}" "${archive}" archive_notice)
      if(archive_notice EQUAL -1)
        message(FATAL_ERROR "Static runtime notice inputs omitted ${archive}")
      endif()
    endforeach()
    # Native Debian/Ubuntu toolchains provide complete notices through dpkg.
    # Other distributions and source SDK wrappers may use explicit notices.
    find_program(dpkg_query dpkg-query)
    if(dpkg_query)
      execute_process(COMMAND "${fixture_CMAKE_CXX_COMPILER}" -print-file-name=libstdc++.a
        OUTPUT_VARIABLE archive OUTPUT_STRIP_TRAILING_WHITESPACE)
      file(REAL_PATH "${archive}" archive)
      execute_process(COMMAND "${dpkg_query}" -S "${archive}" RESULT_VARIABLE owned
        OUTPUT_VARIABLE owner ERROR_QUIET)
      if(owned EQUAL 0)
        string(REGEX MATCH "^[^:\r\n]+" owner "${owner}")
        if(EXISTS "/usr/share/doc/${owner}/copyright" AND
            NOT EXISTS "${relocated}/share/doc/datapump/runtime-notices/${owner}-copyright.txt")
          message(FATAL_ERROR "Packaged static libstdc++ lost its complete copyright notice")
        endif()
      endif()
    endif()
  endif()
endforeach()

foreach(mode nonportable sanitizer)
  set(options -DDATAPUMP_PORTABLE=OFF)
  if(mode STREQUAL "sanitizer")
    set(options -DDATAPUMP_SANITIZERS=ON)
  endif()
  checked("Configure ${mode} policy" "${CMAKE_COMMAND}" -S "${source}"
    -B "${BINARY_DIR}/${mode}" ${options} ${compiler_options})
  file(READ "${BINARY_DIR}/${mode}/policy.txt" policy)
  if(NOT policy MATCHES "enabled=OFF" OR policy MATCHES "static-lib|exclude-libs")
    message(FATAL_ERROR "${mode} incorrectly selected static GNU runtime: ${policy}")
  endif()
endforeach()
