cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../tools/gui-smoke-timeout.cmake")
set(gui_smoke_options "")
if(DEFINED GUI_SMOKE_TIMEOUT)
  list(APPEND gui_smoke_options "-DGUI_SMOKE_TIMEOUT=${GUI_SMOKE_TIMEOUT}")
endif()
if(NOT DEFINED BUILD_DIR)
  message(FATAL_ERROR "Provide -DBUILD_DIR=/path/to/native/build")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
if(NOT DEFINED CONFIG)
  set(CONFIG Release)
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identifier)
set(scratch "${BUILD_DIR}/package-tests/${identifier}")
set(original "${scratch}/original installation")
set(relocated "${scratch}/offline destination/Data Pump with spaces")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config "${CONFIG}" --prefix "${original}"
  RESULT_VARIABLE installed OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT installed EQUAL 0)
  message(FATAL_ERROR "Native installation failed:\n${output}\n${error}")
endif()
file(MAKE_DIRECTORY "${relocated}")
file(COPY "${original}/" DESTINATION "${relocated}")
file(RENAME "${original}" "${scratch}/unavailable original")
set(manuals pump pump-fast)
foreach(frontend datapump-gui datapump-tui datapump-fb)
  if(EXISTS "${relocated}/bin/${frontend}" OR EXISTS "${relocated}/bin/${frontend}.exe")
    list(APPEND manuals ${frontend})
  endif()
endforeach()
foreach(manual IN LISTS manuals)
  set(installed_manual "${relocated}/share/man/man1/${manual}.1")
  if(NOT EXISTS "${installed_manual}")
    message(FATAL_ERROR "Native installation omitted the ${manual}(1) manual")
  endif()
  file(SHA256 "${installed_manual}" installed_hash)
  file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../docs/man/${manual}.1" source_hash)
  if(NOT installed_hash STREQUAL source_hash)
    message(FATAL_ERROR "Installed ${manual}(1) differs from its source")
  endif()
endforeach()
set(verifier "${CMAKE_CURRENT_LIST_DIR}/../tools/verify-native-package.cmake")
if(EXISTS "${relocated}/bin/datapump-fb" OR EXISTS "${relocated}/bin/datapump-fb.exe")
  set(font_notice "${relocated}/share/doc/datapump/framebuffer/DejaVu-LICENSE")
  if(NOT EXISTS "${font_notice}")
    message(FATAL_ERROR "Framebuffer installation omitted the font redistribution notice")
  endif()
  file(SHA256 "${font_notice}" installed_hash)
  file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../third_party/rev/resources/DejaVu-LICENSE" source_hash)
  if(NOT installed_hash STREQUAL source_hash)
    message(FATAL_ERROR "Installed framebuffer font notice differs from its source")
  endif()
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" "-DBUILD_DIR=${BUILD_DIR}"
  "-DGUI_SMOKE=${GUI_SMOKE}" -DREQUIRE_MANUALS=ON ${gui_smoke_options} -P "${verifier}"
  RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT verified EQUAL 0)
  message(FATAL_ERROR "Native relocation failed:\n${output}\n${error}")
endif()
# Tampering and unlisted additions must be distinguished from a verified copy.
set(victim "${relocated}/bin/pump${CMAKE_EXECUTABLE_SUFFIX}")
if(WIN32)
  set(victim "${relocated}/bin/pump.exe")
endif()
file(COPY_FILE "${victim}" "${scratch}/original-pump")
file(APPEND "${victim}" "tampered")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE tampering OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(tampering EQUAL 0 OR NOT error MATCHES "Modified package file")
  message(FATAL_ERROR "Native package verification failed to reject modified content")
endif()
file(COPY_FILE "${scratch}/original-pump" "${victim}")
# A self-consistent inventory is insufficient when a required manual is absent.
file(READ "${relocated}/manifest.sha256" complete_manifest)
# A self-consistent manifest must not conceal a dropped, enabled frontend.
foreach(frontend datapump-tui datapump-fb)
  set(binary_name "${frontend}")
  if(WIN32)
    string(APPEND binary_name ".exe")
  endif()
  if(EXISTS "${relocated}/bin/${binary_name}")
    file(RENAME "${relocated}/bin/${binary_name}" "${scratch}/${binary_name}")
    string(REPLACE "." "\\." binary_pattern "${binary_name}")
    string(REGEX REPLACE "[0-9a-f]+  bin/${binary_pattern}\n" "" missing_binary_manifest "${complete_manifest}")
    file(WRITE "${relocated}/manifest.sha256" "${missing_binary_manifest}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
      RESULT_VARIABLE missing_binary OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(missing_binary EQUAL 0 OR NOT error MATCHES "lacks the enabled ${frontend}")
      message(FATAL_ERROR "Native package verification accepted a missing enabled ${frontend}")
    endif()
    file(RENAME "${scratch}/${binary_name}" "${relocated}/bin/${binary_name}")
    file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
  endif()
endforeach()
if(EXISTS "${relocated}/share/terminfo/x/xterm-256color")
  file(RENAME "${relocated}/share/terminfo/x/xterm-256color" "${scratch}/xterm-256color")
  string(REGEX REPLACE "[0-9a-f]+  share/terminfo/x/xterm-256color\n" "" missing_terminal_manifest "${complete_manifest}")
  file(WRITE "${relocated}/manifest.sha256" "${missing_terminal_manifest}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
    RESULT_VARIABLE missing_terminal OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(missing_terminal EQUAL 0 OR NOT error MATCHES "lacks the xterm-256color terminal description")
    message(FATAL_ERROR "Native package verification accepted missing terminal data")
  endif()
  file(RENAME "${scratch}/xterm-256color" "${relocated}/share/terminfo/x/xterm-256color")
  file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
endif()
foreach(name IN LISTS manuals)
  set(manual "${relocated}/share/man/man1/${name}.1")
  file(RENAME "${manual}" "${scratch}/original-${name}.1")
  string(REGEX REPLACE "[0-9a-f]+  share/man/man1/${name}\\.1\n" "" missing_manual_manifest "${complete_manifest}")
  file(WRITE "${relocated}/manifest.sha256" "${missing_manual_manifest}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
    RESULT_VARIABLE missing_manual OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(missing_manual EQUAL 0 OR NOT error MATCHES "lacks the ${name}")
    message(FATAL_ERROR "Native package verification accepted a missing ${name} manual")
  endif()
  file(RENAME "${scratch}/original-${name}.1" "${manual}")
  file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
endforeach()
# Current helpers can still certify the inventory of historical releases, but
# newly produced archives must opt into the complete manual requirement.
foreach(manual IN LISTS manuals)
  file(RENAME "${relocated}/share/man/man1/${manual}.1" "${scratch}/${manual}.1")
endforeach()
string(REGEX REPLACE "[0-9a-f]+  share/man/man1/[^\n]+\n" "" historical_manifest "${complete_manifest}")
file(WRITE "${relocated}/manifest.sha256" "${historical_manifest}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE historical OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT historical EQUAL 0 OR NOT output MATCHES "Historical native package")
  message(FATAL_ERROR "Historical package without manuals failed inventory verification: ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -DREQUIRE_MANUALS=ON -P "${verifier}"
  RESULT_VARIABLE missing_manuals OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(missing_manuals EQUAL 0 OR NOT error MATCHES "lacks the pump")
  message(FATAL_ERROR "New package verification accepted an absent manual set")
endif()
foreach(manual IN LISTS manuals)
  file(RENAME "${scratch}/${manual}.1" "${relocated}/share/man/man1/${manual}.1")
endforeach()
file(WRITE "${relocated}/manifest.sha256" "${complete_manifest}")
file(WRITE "${relocated}/unexpected-file.txt" "not part of the installation")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${relocated}" -DVERIFY_ONLY=ON -P "${verifier}"
  RESULT_VARIABLE extra OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(extra EQUAL 0 OR NOT error MATCHES "unrecorded")
  message(FATAL_ERROR "Native package verification failed to reject an unrecorded file")
endif()
message(STATUS "Native relocation and package corruption checks passed: ${relocated}")
