cmake_minimum_required(VERSION 3.21)
set(source "${CMAKE_CURRENT_LIST_DIR}/../third_party/xz")
file(STRINGS "${source}/UPSTREAM.sha256" files)
set(recorded "")
foreach(entry IN LISTS files)
  if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
    message(FATAL_ERROR "Invalid pinned liblzma file entry")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(path "${CMAKE_MATCH_2}")
  if(NOT EXISTS "${source}/${path}")
    message(FATAL_ERROR "Missing pinned liblzma source: ${path}")
  endif()
  file(SHA256 "${source}/${path}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Modified pinned liblzma source: ${path}")
  endif()
  list(APPEND recorded "${path}")
endforeach()
file(GLOB_RECURSE actual LIST_DIRECTORIES FALSE RELATIVE "${source}" "${source}/*")
list(REMOVE_ITEM actual README.datapump.md UPSTREAM.sha256)
list(SORT actual)
list(SORT recorded)
if(NOT actual STREQUAL recorded)
  message(FATAL_ERROR "Unrecorded pinned liblzma source files")
endif()
message(STATUS "Pinned offline liblzma source verified")
