# Relocatable, explicitly prepared Linux SDK. No downloads or SDK mutations.
# Keep this file usable inside CMake's try_compile subprojects.
if(NOT DATAPUMP_SDK_ROOT)
  message(FATAL_ERROR "Set DATAPUMP_SDK_ROOT, or use ./build.sh --sdk PATH")
endif()
file(REAL_PATH "${DATAPUMP_SDK_ROOT}" _datapump_sdk)
set(DATAPUMP_SDK_ROOT "${_datapump_sdk}" CACHE PATH "Prepared DataPump source SDK" FORCE)
set(_datapump_sdk_metadata "${DATAPUMP_SDK_ROOT}/share/datapump-sdk")
if(NOT EXISTS "${_datapump_sdk_metadata}/manifest.json" OR
    NOT EXISTS "${_datapump_sdk_metadata}/relocated-root.txt")
  message(FATAL_ERROR "SDK metadata is missing. Use tools/build-sdk.py install to prepare an SDK before configuring.")
endif()
file(READ "${_datapump_sdk_metadata}/relocated-root.txt" _datapump_relocated)
string(STRIP "${_datapump_relocated}" _datapump_relocated)
if(NOT _datapump_relocated STREQUAL DATAPUMP_SDK_ROOT)
  message(FATAL_ERROR "SDK was moved without relocation. Use tools/build-sdk.py install before configuring.")
endif()
file(READ "${_datapump_sdk_metadata}/manifest.json" _datapump_manifest)
file(SHA256 "${_datapump_sdk_metadata}/manifest.json" _datapump_manifest_sha)
string(JSON _datapump_schema GET "${_datapump_manifest}" schema_version)
if(NOT _datapump_schema EQUAL 1)
  message(FATAL_ERROR "Unsupported SDK manifest schema: ${_datapump_schema}")
endif()
if(DEFINED DATAPUMP_CONFIGURED_SDK_ROOT AND
    NOT DATAPUMP_CONFIGURED_SDK_ROOT STREQUAL DATAPUMP_SDK_ROOT)
  message(FATAL_ERROR "SDK root changed. Use a fresh --build-dir to avoid mixing cached libraries.")
endif()
if(DEFINED DATAPUMP_CONFIGURED_SDK_MANIFEST AND
    NOT DATAPUMP_CONFIGURED_SDK_MANIFEST STREQUAL _datapump_manifest_sha)
  message(FATAL_ERROR "SDK manifest changed. Use a fresh --build-dir to avoid mixing cached libraries.")
endif()
set(DATAPUMP_CONFIGURED_SDK_ROOT "${DATAPUMP_SDK_ROOT}" CACHE INTERNAL "SDK used by this build")
set(DATAPUMP_CONFIGURED_SDK_MANIFEST "${_datapump_manifest_sha}" CACHE INTERNAL "SDK manifest used by this build")
string(JSON DATAPUMP_SDK_ID GET "${_datapump_manifest}" id)
string(JSON DATAPUMP_SDK_GLIBC_MAX GET "${_datapump_manifest}" baseline glibc)
set(DATAPUMP_SDK_ID "${DATAPUMP_SDK_ID}" CACHE INTERNAL "SDK recipe identity" FORCE)
set(DATAPUMP_SDK_GLIBC_MAX "${DATAPUMP_SDK_GLIBC_MAX}" CACHE INTERNAL "SDK glibc ABI ceiling" FORCE)
if(NOT DATAPUMP_SDK_GLIBC_MAX MATCHES "^[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR "Invalid SDK glibc baseline")
endif()
string(JSON _datapump_backend_count ERROR_VARIABLE _datapump_backend_error
  LENGTH "${_datapump_manifest}" supported_backends)
if(NOT _datapump_backend_error AND DATAPUMP_BUILD_GUI)
  set(_datapump_supported_backends)
  if(_datapump_backend_count GREATER 0)
    math(EXPR _datapump_backend_last "${_datapump_backend_count} - 1")
    foreach(index RANGE 0 ${_datapump_backend_last})
      string(JSON backend GET "${_datapump_manifest}" supported_backends ${index})
      list(APPEND _datapump_supported_backends "${backend}")
    endforeach()
  endif()
  if(NOT DATAPUMP_GUI_BACKEND IN_LIST _datapump_supported_backends)
    message(FATAL_ERROR "SDK does not support the ${DATAPUMP_GUI_BACKEND} GUI backend. Supported backends: ${_datapump_supported_backends}")
  endif()
endif()

# Only SDK-contained, relative paths are accepted. This also catches escaping
# symlinks, which would otherwise produce an apparently isolated host build.
function(_datapump_sdk_path field output)
  string(JSON relative GET "${_datapump_manifest}" target "${field}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)|[;\\\\]" OR relative STREQUAL "")
    message(FATAL_ERROR "Invalid SDK target ${field}: ${relative}")
  endif()
  set(path "${DATAPUMP_SDK_ROOT}/${relative}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "SDK target ${field} is missing: ${path}")
  endif()
  file(REAL_PATH "${path}" resolved)
  string(FIND "${resolved}" "${DATAPUMP_SDK_ROOT}/" prefix)
  if(NOT prefix EQUAL 0)
    message(FATAL_ERROR "SDK target ${field} escapes its root: ${path}")
  endif()
  set("${output}" "${path}" PARENT_SCOPE)
endfunction()
_datapump_sdk_path(sysroot _datapump_sysroot)
_datapump_sdk_path(c_compiler _datapump_cc)
_datapump_sdk_path(cxx_compiler _datapump_cxx)
string(JSON _datapump_processor GET "${_datapump_manifest}" target processor)
string(JSON DATAPUMP_SDK_TARGET GET "${_datapump_manifest}" target triple)
set(DATAPUMP_SDK_TARGET "${DATAPUMP_SDK_TARGET}" CACHE INTERNAL "SDK target triple" FORCE)
if(NOT IS_DIRECTORY "${_datapump_sysroot}")
  message(FATAL_ERROR "SDK sysroot is not a directory: ${_datapump_sysroot}")
endif()

foreach(variable CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH LIBRARY_PATH GCC_EXEC_PREFIX COMPILER_PATH)
  if(NOT "$ENV{${variable}}" STREQUAL "")
    message(FATAL_ERROR "Unset ${variable}: it can inject host files into the source SDK build.")
  endif()
endforeach()
if(DATAPUMP_DEPENDENCY_PREFIX)
  message(FATAL_ERROR "Source SDK and DATAPUMP_DEPENDENCY_PREFIX cannot be combined.")
endif()
foreach(language C CXX)
  if(language STREQUAL "C")
    set(compiler "${_datapump_cc}")
  else()
    set(compiler "${_datapump_cxx}")
  endif()
  if(DEFINED CMAKE_${language}_COMPILER AND NOT CMAKE_${language}_COMPILER STREQUAL compiler)
    message(FATAL_ERROR "SDK owns the ${language} compiler. Remove the conflicting override and use a fresh --build-dir.")
  endif()
  set(CMAKE_${language}_COMPILER "${compiler}" CACHE FILEPATH "SDK ${language} compiler")
endforeach()
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${_datapump_processor}")
set(CMAKE_SYSROOT "${_datapump_sysroot}")
set(CMAKE_FIND_ROOT_PATH "${_datapump_sysroot}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF)

# pkg-config is a host tool, but all metadata and paths must describe the target.
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${_datapump_sysroot}")
set(ENV{PKG_CONFIG_LIBDIR} "${_datapump_sysroot}/usr/lib/pkgconfig:${_datapump_sysroot}/usr/share/pkgconfig:${_datapump_sysroot}/lib/pkgconfig")
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH FALSE)
if(EXISTS "${DATAPUMP_SDK_ROOT}/bin/pkg-config")
  set(PKG_CONFIG_EXECUTABLE "${DATAPUMP_SDK_ROOT}/bin/pkg-config" CACHE FILEPATH "SDK pkg-config" FORCE)
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES DATAPUMP_SDK_ROOT)
