# Explicitly prepared Wasm SDK; no application-time downloads or host libraries.
if(NOT DATAPUMP_WASM_SDK_ROOT)
  message(FATAL_ERROR "Use ./build.sh --wasm-sdk PATH with an explicitly prepared SDK")
endif()
file(REAL_PATH "${DATAPUMP_WASM_SDK_ROOT}" DATAPUMP_WASM_SDK_ROOT)
set(DATAPUMP_WASM_SDK_ROOT "${DATAPUMP_WASM_SDK_ROOT}" CACHE PATH "Prepared Wasm SDK" FORCE)
set(_wasm_metadata "${DATAPUMP_WASM_SDK_ROOT}/share/datapump-wasm-sdk")
if(NOT EXISTS "${_wasm_metadata}/manifest.json" OR NOT EXISTS "${_wasm_metadata}/relocated-root.txt")
  message(FATAL_ERROR "Wasm SDK is not prepared: missing metadata")
endif()
file(READ "${_wasm_metadata}/relocated-root.txt" _wasm_location)
string(STRIP "${_wasm_location}" _wasm_location)
if(NOT _wasm_location STREQUAL DATAPUMP_WASM_SDK_ROOT)
  message(FATAL_ERROR "Wasm SDK moved after preparation; prepare a new destination")
endif()
file(READ "${_wasm_metadata}/manifest.json" _wasm_manifest)
file(SHA256 "${_wasm_metadata}/manifest.json" _wasm_identity)
string(JSON _wasm_schema GET "${_wasm_manifest}" schema_version)
string(JSON _wasm_target GET "${_wasm_manifest}" target)
if(NOT _wasm_schema EQUAL 1 OR NOT _wasm_target STREQUAL "wasm32-emscripten")
  message(FATAL_ERROR "Unsupported Wasm SDK manifest")
endif()
string(JSON _wasm_entropy ERROR_VARIABLE _wasm_entropy_error GET "${_wasm_manifest}" entropy_capability)
string(JSON _wasm_entropy_probe ERROR_VARIABLE _wasm_probe_error GET "${_wasm_manifest}" entropy_probe)
if(_wasm_entropy_error OR _wasm_probe_error OR
   NOT _wasm_entropy STREQUAL "emscripten-getentropy-webcrypto-v1" OR
   NOT _wasm_entropy_probe STREQUAL "passed")
  message(FATAL_ERROR "Wasm SDK lacks qualified browser entropy; prepare a new SDK destination with the current recipe (existing SDKs must not be modified)")
endif()
foreach(field ROOT MANIFEST)
  if(field STREQUAL "ROOT")
    set(value "${DATAPUMP_WASM_SDK_ROOT}")
  else()
    set(value "${_wasm_identity}")
  endif()
  if(DEFINED DATAPUMP_CONFIGURED_WASM_SDK_${field} AND NOT DATAPUMP_CONFIGURED_WASM_SDK_${field} STREQUAL value)
    message(FATAL_ERROR "Wasm SDK ${field} changed; use a fresh build directory")
  endif()
  set(DATAPUMP_CONFIGURED_WASM_SDK_${field} "${value}" CACHE INTERNAL "Wasm SDK identity")
endforeach()
function(_datapump_wasm_path field output)
  string(JSON relative GET "${_wasm_manifest}" "${field}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)|[;\\\\]" OR relative STREQUAL "")
    message(FATAL_ERROR "Invalid Wasm SDK path: ${field}")
  endif()
  set(path "${DATAPUMP_WASM_SDK_ROOT}/${relative}")
  file(REAL_PATH "${path}" resolved)
  string(FIND "${resolved}" "${DATAPUMP_WASM_SDK_ROOT}/" prefix)
  if(NOT prefix EQUAL 0 OR NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing or escaping Wasm SDK path: ${field}")
  endif()
  set("${output}" "${path}" PARENT_SCOPE)
endfunction()
_datapump_wasm_path(toolchain _wasm_toolchain)
_datapump_wasm_path(compiler _wasm_cc)
_datapump_wasm_path(cxx_compiler _wasm_cxx)
_datapump_wasm_path(openssl_include _wasm_crypto_include)
_datapump_wasm_path(openssl_crypto _wasm_crypto_library)
file(SHA256 "${_wasm_crypto_library}" _wasm_crypto_hash)
string(JSON _wasm_expected_crypto_hash GET "${_wasm_manifest}" openssl_crypto_sha256)
if(NOT _wasm_crypto_hash STREQUAL _wasm_expected_crypto_hash)
  message(FATAL_ERROR "Wasm SDK OpenSSL checksum mismatch")
endif()
foreach(variable CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH LIBRARY_PATH EMCC_CFLAGS EMMAKEN_CFLAGS)
  if(NOT "$ENV{${variable}}" STREQUAL "")
    message(FATAL_ERROR "Unset ${variable}: Wasm SDK compiler/search paths must remain isolated")
  endif()
endforeach()
if(DATAPUMP_DEPENDENCY_PREFIX OR DATAPUMP_SDK_ROOT)
  message(FATAL_ERROR "The Wasm SDK cannot be mixed with native dependency roots")
endif()
set(ENV{EM_CONFIG} "${DATAPUMP_WASM_SDK_ROOT}/.emscripten")
set(ENV{EM_CACHE} "${DATAPUMP_WASM_SDK_ROOT}/cache")
set(ENV{EM_FROZEN_CACHE} "1")
include("${_wasm_toolchain}")
if(NOT CMAKE_C_COMPILER STREQUAL _wasm_cc OR NOT CMAKE_CXX_COMPILER STREQUAL _wasm_cxx)
  message(FATAL_ERROR "Wasm SDK compiler override detected")
endif()
list(APPEND CMAKE_FIND_ROOT_PATH "${DATAPUMP_WASM_SDK_ROOT}/target")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF)
set(OPENSSL_USE_STATIC_LIBS ON CACHE BOOL "Wasm SDK crypto is static" FORCE)
set(OPENSSL_INCLUDE_DIR "${_wasm_crypto_include}" CACHE PATH "Wasm OpenSSL headers" FORCE)
set(OPENSSL_CRYPTO_LIBRARY "${_wasm_crypto_library}" CACHE FILEPATH "Wasm OpenSSL static library" FORCE)
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "${DATAPUMP_WASM_SDK_ROOT}/target/lib/pkgconfig")
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH FALSE)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES DATAPUMP_WASM_SDK_ROOT)
