# Configured by Portable.cmake and executed at installation/CPack time.
cmake_minimum_required(VERSION 3.21)
set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM [==[@DATAPUMP_RUNTIME_PLATFORM@]==])
set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL [==[@DATAPUMP_RUNTIME_TOOL@]==])
set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND [==[@DATAPUMP_RUNTIME_COMMAND@]==])
include([==[@DATAPUMP_POLICY_FILE@]==])
set(package_root "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}")
set(executable_names [==[@DATAPUMP_EXECUTABLE_NAMES@]==])
set(search_directories [==[@DATAPUMP_SEARCH_DIRS@]==])
set(optional_alsa [==[@DATAPUMP_ALSA_LIBRARY@]==])
set(static_notice_sources [==[@DATAPUMP_NOTICE_INPUTS@]==])
set(extra_notice_files [==[@DATAPUMP_NOTICE_FILES@]==])
set(sdk_root [==[@DATAPUMP_PACKAGE_SDK_ROOT@]==])
set(sdk_sysroot [==[@DATAPUMP_PACKAGE_SYSROOT@]==])
set(sdk_external_libraries [==[@DATAPUMP_SDK_EXTERNAL_LIBRARIES@]==])
if(sdk_root)
  include([==[@DATAPUMP_SDK_RUNTIME_HELPER@]==])
  datapump_sdk_validate_path("${sdk_sysroot}" "${sdk_root}")
  foreach(source IN LISTS sdk_external_libraries)
    datapump_sdk_validate_path("${source}" "${sdk_sysroot}")
  endforeach()
endif()
set(executables "")
foreach(name IN LISTS executable_names)
  list(APPEND executables "${package_root}/bin/${name}")
endforeach()
set(extra_roots "")
if(sdk_root AND optional_alsa)
  datapump_sdk_validate_path("${optional_alsa}" "${sdk_sysroot}")
endif()
if(optional_alsa AND EXISTS "${optional_alsa}")
  list(APPEND extra_roots "${optional_alsa}")
endif()
if(sdk_root)
  datapump_sdk_runtime_dependencies(resolved
    SYSROOT "${sdk_sysroot}" OBJDUMP "${CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND}"
    EXECUTABLES ${executables} LIBRARIES ${extra_roots}
    EXCLUDE_REGEXES ${DATAPUMP_OS_LIBRARIES})
else()
  file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES ${executables} LIBRARIES ${extra_roots}
    DIRECTORIES ${search_directories}
    PRE_EXCLUDE_REGEXES ${DATAPUMP_OS_LIBRARIES}
    RESOLVED_DEPENDENCIES_VAR resolved
    UNRESOLVED_DEPENDENCIES_VAR unresolved
    CONFLICTING_DEPENDENCIES_PREFIX conflicts)
  if(unresolved OR conflicts_FILENAMES)
    message(FATAL_ERROR "Incomplete portable dependency set. Missing: ${unresolved}; conflicting: ${conflicts_FILENAMES}")
  endif()
endif()
list(APPEND resolved ${extra_roots})
list(REMOVE_DUPLICATES resolved)
if(WIN32)
  set(library_destination "${package_root}/bin")
else()
  set(library_destination "${package_root}/lib")
endif()
file(MAKE_DIRECTORY "${library_destination}")
set(notice_directory "${package_root}/share/doc/datapump/runtime-notices")
file(MAKE_DIRECTORY "${notice_directory}")
set(provenance "Native Data Pump @PROJECT_VERSION@\nPlatform: @CMAKE_SYSTEM_NAME@ @CMAKE_SYSTEM_PROCESSOR@\nCompiler: @CMAKE_CXX_COMPILER_ID@ @CMAKE_CXX_COMPILER_VERSION@\nOperating-system ABI libraries are excluded; see docs/offline-installation.md.\n\n")
if(sdk_root)
  set(sdk_metadata "${sdk_root}/share/datapump-sdk")
  datapump_sdk_validate_path("${sdk_metadata}/manifest.json" "${sdk_root}")
  datapump_sdk_validate_path("${sdk_metadata}/licenses" "${sdk_root}")
  file(GLOB_RECURSE sdk_notices LIST_DIRECTORIES TRUE RELATIVE "${sdk_metadata}/licenses"
    "${sdk_metadata}/licenses/*")
  set(notice_count 0)
  foreach(relative IN LISTS sdk_notices)
    set(source "${sdk_metadata}/licenses/${relative}")
    datapump_sdk_validate_path("${source}" "${sdk_root}")
    if(IS_DIRECTORY "${source}")
      if(IS_SYMLINK "${source}")
        message(FATAL_ERROR "SDK license directories must not be symlinks: ${source}")
      endif()
      continue()
    endif()
    math(EXPR notice_count "${notice_count} + 1")
    get_filename_component(directory "${relative}" DIRECTORY)
    get_filename_component(name "${relative}" NAME)
    file(REAL_PATH "${source}" real_source)
    file(INSTALL DESTINATION "${notice_directory}/sdk/licenses/${directory}" TYPE FILE
      FILES "${real_source}" RENAME "${name}")
  endforeach()
  if(notice_count EQUAL 0)
    message(FATAL_ERROR "SDK license directory is empty: ${sdk_metadata}/licenses")
  endif()
  file(REAL_PATH "${sdk_metadata}/manifest.json" sdk_manifest)
  file(INSTALL DESTINATION "${notice_directory}/sdk" TYPE FILE FILES "${sdk_manifest}" RENAME manifest.json)
  file(SHA256 "${sdk_manifest}" sdk_manifest_sha256)
  string(APPEND provenance "SDK manifest SHA-256: ${sdk_manifest_sha256}\nSDK: ${sdk_root}\nSysroot: ${sdk_sysroot}\n\n")
else()
  find_program(dpkg_query dpkg-query)
endif()
function(install_runtime_notice source name)
  file(REAL_PATH "${source}" notice)
  file(INSTALL DESTINATION "${notice_directory}" TYPE FILE FILES "${notice}" RENAME "${name}")
  # Debian copyright notices refer to complete license texts in this directory.
  if(sdk_root)
    # SDK notices must be self-contained; never follow references into host /usr.
    return()
  endif()
  file(READ "${notice}" contents)
  string(REGEX MATCHALL "/usr/share/common-licenses/[A-Za-z0-9.+-]+" referenced "${contents}")
  list(REMOVE_DUPLICATES referenced)
  foreach(reference IN LISTS referenced)
    if(EXISTS "${reference}")
      file(REAL_PATH "${reference}" original)
      get_filename_component(filename "${reference}" NAME)
      file(INSTALL DESTINATION "${notice_directory}/license-texts" TYPE FILE
        FILES "${original}" RENAME "${filename}")
    endif()
  endforeach()
endfunction()
foreach(source IN LISTS resolved)
  if(sdk_root)
    datapump_sdk_validate_path("${source}" "${sdk_sysroot}")
  endif()
  file(REAL_PATH "${source}" real_source)
  # Materialize every name in a source symlink chain. The installed tree never
  # keeps an absolute link back to a build computer.
  set(current "${source}")
  set(visited "")
  while(TRUE)
    if(current IN_LIST visited)
      message(FATAL_ERROR "Cyclic native-library symlink: ${source}")
    endif()
    list(APPEND visited "${current}")
    get_filename_component(name "${current}" NAME)
    set(destination "${library_destination}/${name}")
    string(SHA256 name_key "${name}")
    file(SHA256 "${real_source}" incoming)
    if(DEFINED "copied_${name_key}")
      if(NOT "${copied_${name_key}}" STREQUAL incoming)
        message(FATAL_ERROR "Conflicting installed native library: ${name}")
      endif()
    else()
      set("copied_${name_key}" "${incoming}")
      file(INSTALL DESTINATION "${library_destination}" TYPE FILE
        FILES "${real_source}" RENAME "${name}")
      if(NOT WIN32)
        file(RPATH_REMOVE FILE "${destination}")
      endif()
    endif()
    if(NOT IS_SYMLINK "${current}")
      break()
    endif()
    file(READ_SYMLINK "${current}" following)
    if(IS_ABSOLUTE "${following}")
      set(current "${following}")
    else()
      get_filename_component(parent "${current}" DIRECTORY)
      set(current "${parent}/${following}")
    endif()
  endwhile()
  string(APPEND provenance "${source}\n")
endforeach()
if(sdk_root)
  set(notice_sources "")
else()
  set(notice_sources ${resolved} ${static_notice_sources})
endif()
list(REMOVE_DUPLICATES notice_sources)
foreach(source IN LISTS notice_sources)
  if(NOT EXISTS "${source}")
    continue()
  endif()
  file(REAL_PATH "${source}" real_source)
  if(dpkg_query)
    execute_process(COMMAND "${dpkg_query}" -S "${real_source}"
      OUTPUT_VARIABLE ownership ERROR_QUIET RESULT_VARIABLE found_package)
    if(found_package AND real_source MATCHES "^/lib/")
      execute_process(COMMAND "${dpkg_query}" -S "/usr${real_source}"
        OUTPUT_VARIABLE ownership ERROR_QUIET RESULT_VARIABLE found_package)
    endif()
    if(NOT found_package)
      string(REGEX MATCH "^[^:\r\n]+" package "${ownership}")
      set(copyright "/usr/share/doc/${package}/copyright")
      if(EXISTS "${copyright}")
        install_runtime_notice("${copyright}" "${package}-copyright.txt")
      endif()
    endif()
  endif()
endforeach()
set(notice_index 0)
foreach(notice IN LISTS extra_notice_files)
  if(sdk_root)
    datapump_sdk_validate_path("${notice}" "${sdk_root}")
  endif()
  if(NOT EXISTS "${notice}")
    message(FATAL_ERROR "Specified native runtime notice is unavailable locally: ${notice}")
  endif()
  get_filename_component(name "${notice}" NAME)
  math(EXPR notice_index "${notice_index} + 1")
  install_runtime_notice("${notice}" "local-${notice_index}-${name}")
endforeach()
file(WRITE "${package_root}/share/doc/datapump/runtime-info.txt" "${provenance}")
file(GLOB_RECURSE inventory RELATIVE "${package_root}" LIST_DIRECTORIES FALSE "${package_root}/*")
list(SORT inventory)
set(manifest "")
foreach(relative IN LISTS inventory)
  if(relative STREQUAL "manifest.sha256")
    continue()
  endif()
  if(IS_SYMLINK "${package_root}/${relative}")
    message(FATAL_ERROR "Portable package unexpectedly contains a symlink: ${relative}")
  endif()
  file(SHA256 "${package_root}/${relative}" digest)
  string(APPEND manifest "${digest}  ${relative}\n")
endforeach()
file(WRITE "${package_root}/manifest.sha256" "${manifest}")
message(STATUS "Created native portable installation: ${package_root}")
