# Developer verification; the installed application itself does not need CMake.
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/gui-smoke-timeout.cmake")
if(NOT DEFINED PACKAGE_ROOT)
  message(FATAL_ERROR "Provide -DPACKAGE_ROOT=/path/to/installed/DataPump")
endif()
get_filename_component(PACKAGE_ROOT "${PACKAGE_ROOT}" ABSOLUTE)
file(REAL_PATH "${PACKAGE_ROOT}" PACKAGE_ROOT)
file(STRINGS "${PACKAGE_ROOT}/manifest.sha256" entries ENCODING UTF-8)
set(recorded "")
foreach(entry IN LISTS entries)
  if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
    message(FATAL_ERROR "Malformed package inventory entry")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(relative "${CMAKE_MATCH_2}")
  string(LENGTH "${expected}" digest_length)
  if(NOT digest_length EQUAL 64 OR IS_ABSOLUTE "${relative}" OR
      relative MATCHES "(^|/)\\.\\.(/|$)" OR IS_SYMLINK "${PACKAGE_ROOT}/${relative}")
    message(FATAL_ERROR "Invalid package inventory path: ${relative}")
  endif()
  if(NOT EXISTS "${PACKAGE_ROOT}/${relative}")
    message(FATAL_ERROR "Missing package file: ${relative}")
  endif()
  file(SHA256 "${PACKAGE_ROOT}/${relative}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Modified package file: ${relative}")
  endif()
  list(APPEND recorded "${relative}")
endforeach()
file(GLOB_RECURSE actual_files RELATIVE "${PACKAGE_ROOT}" LIST_DIRECTORIES FALSE "${PACKAGE_ROOT}/*")
list(REMOVE_ITEM actual_files "manifest.sha256")
list(SORT recorded)
list(SORT actual_files)
if(NOT actual_files STREQUAL recorded)
  message(FATAL_ERROR "Package inventory has missing, duplicate, or unrecorded files")
endif()
if(VERIFY_ONLY)
  message(STATUS "Native package inventory verified")
  return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/RuntimePolicy.cmake")
if(DEFINED BUILD_DIR AND EXISTS "${BUILD_DIR}/datapump-runtime-tool.cmake")
  include("${BUILD_DIR}/datapump-runtime-tool.cmake")
endif()
set(extension "")
if(WIN32)
  set(extension ".exe")
endif()
set(pump "${PACKAGE_ROOT}/bin/pump${extension}")
set(gui "${PACKAGE_ROOT}/bin/datapump-gui${extension}")
set(executables "${pump}")
if(EXISTS "${gui}")
  list(APPEND executables "${gui}")
endif()
file(GLOB extra_roots "${PACKAGE_ROOT}/lib/libasound.so*")
file(GET_RUNTIME_DEPENDENCIES EXECUTABLES ${executables} LIBRARIES ${extra_roots}
  PRE_EXCLUDE_REGEXES ${DATAPUMP_OS_LIBRARIES}
  RESOLVED_DEPENDENCIES_VAR dependencies UNRESOLVED_DEPENDENCIES_VAR missing
  CONFLICTING_DEPENDENCIES_PREFIX conflicts)
if(missing OR conflicts_FILENAMES)
  message(FATAL_ERROR "Relocated package has unresolved/conflicting native dependencies: ${missing}; ${conflicts_FILENAMES}")
endif()
foreach(dependency IN LISTS dependencies)
  string(TOLOWER "${dependency}" dependency_name)
  if(dependency_name MATCHES "[/\\\\](lib)?lzma[^/\\\\]*\\.(so|dll|dylib)")
    message(FATAL_ERROR "Compression must be linked from pinned static sources: ${dependency}")
  endif()
  file(REAL_PATH "${dependency}" actual)
  set(prefix "${PACKAGE_ROOT}")
  if(WIN32)
    string(TOLOWER "${actual}" actual)
    string(TOLOWER "${prefix}" prefix)
  endif()
  cmake_path(IS_PREFIX prefix "${actual}" NORMALIZE inside)
  if(NOT inside)
    message(FATAL_ERROR "Relocated application depends on a host library: ${dependency}")
  endif()
endforeach()
set(isolated_environment "PATH=" "PYTHONHOME=/nonexistent" "PYTHONPATH=/nonexistent")
if(NOT WIN32)
  list(APPEND isolated_environment "LD_LIBRARY_PATH=")
endif()
function(check_command command_timeout)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${isolated_environment} ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT "${command_timeout}")
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Relocated native command failed: ${ARGN}\n${output}\n${error}")
  endif()
  set(command_output "${output}" PARENT_SCOPE)
endfunction()
check_command(120 "${pump}" --version)
check_command(120 "${pump}" simulate --text "offline native relocation" --snr 18 --json)
string(JSON validated ERROR_VARIABLE json_error GET "${command_output}" validated)
if(json_error OR NOT validated)
  message(FATAL_ERROR "Relocated modem simulation did not return validated content: ${command_output}")
endif()
# Exercise the long codec inside the copied executable with no runtime tools
# or package paths, in addition to the short-message simulation above.
string(REPEAT "portable compressed data pump content " 64 long_text)
check_command(120 "${pump}" simulate --text "${long_text}" --snr 18 --json)
string(JSON validated ERROR_VARIABLE json_error GET "${command_output}" validated)
if(json_error OR NOT validated)
  message(FATAL_ERROR "Relocated long-payload codec failed: ${command_output}")
endif()
if(EXISTS "${gui}")
  check_command(120 "${gui}" --self-check)
  if(GUI_SMOKE)
    if(DEFINED GUI_SMOKE_TIMEOUT)
      check_command("${GUI_SMOKE_PROCESS_TIMEOUT}" "${gui}" --smoke-test
        --smoke-timeout "${GUI_SMOKE_TIMEOUT}")
    else()
      check_command(120 "${gui}" --smoke-test)
    endif()
  endif()
endif()
message(STATUS "Native package inventory, dependency closure, and isolated commands verified")
