# Developer verification; the installed application itself does not need CMake.
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/gui-smoke-timeout.cmake")
if(NOT DEFINED PACKAGE_ROOT)
  message(FATAL_ERROR "Provide -DPACKAGE_ROOT=/path/to/installed/DataPump")
endif()
get_filename_component(PACKAGE_ROOT "${PACKAGE_ROOT}" ABSOLUTE)
file(REAL_PATH "${PACKAGE_ROOT}" PACKAGE_ROOT)
file(STRINGS "${PACKAGE_ROOT}/manifest.sha256" entries ENCODING UTF-8)
set(recorded "")
foreach(entry IN LISTS entries)
  if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
    message(FATAL_ERROR "Malformed package inventory entry")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(relative "${CMAKE_MATCH_2}")
  string(LENGTH "${expected}" digest_length)
  if(NOT digest_length EQUAL 64 OR IS_ABSOLUTE "${relative}" OR
      relative MATCHES "(^|/)\\.\\.(/|$)" OR IS_SYMLINK "${PACKAGE_ROOT}/${relative}")
    message(FATAL_ERROR "Invalid package inventory path: ${relative}")
  endif()
  if(NOT EXISTS "${PACKAGE_ROOT}/${relative}")
    message(FATAL_ERROR "Missing package file: ${relative}")
  endif()
  file(SHA256 "${PACKAGE_ROOT}/${relative}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Modified package file: ${relative}")
  endif()
  list(APPEND recorded "${relative}")
endforeach()
file(GLOB_RECURSE actual_files RELATIVE "${PACKAGE_ROOT}" LIST_DIRECTORIES FALSE "${PACKAGE_ROOT}/*")
list(REMOVE_ITEM actual_files "manifest.sha256")
list(SORT recorded)
list(SORT actual_files)
if(NOT actual_files STREQUAL recorded)
  message(FATAL_ERROR "Package inventory has missing, duplicate, or unrecorded files")
endif()
if(EXISTS "${PACKAGE_ROOT}/share/doc/datapump/build-info.txt")
  file(READ "${PACKAGE_ROOT}/share/doc/datapump/build-info.txt" build_info)
  foreach(pair "TUI|datapump-tui" "Framebuffer|datapump-fb")
    string(REPLACE "|" ";" fields "${pair}")
    list(GET fields 0 feature)
    list(GET fields 1 executable)
    if(REQUIRE_FRONTENDS OR build_info MATCHES "(^|\n)${feature}: ON ")
      if(NOT EXISTS "${PACKAGE_ROOT}/bin/${executable}" AND NOT EXISTS "${PACKAGE_ROOT}/bin/${executable}.exe")
        message(FATAL_ERROR "Native package lacks the enabled ${executable} frontend")
      endif()
    endif()
  endforeach()
  if(build_info MATCHES "(^|\n)TUI: ON \\(ncurses\\)")
    foreach(terminal linux xterm xterm-256color screen screen-256color)
      string(SUBSTRING "${terminal}" 0 1 initial)
      if(NOT "share/terminfo/${initial}/${terminal}" IN_LIST recorded)
        message(FATAL_ERROR "Native package lacks the ${terminal} terminal description")
      endif()
    endforeach()
  endif()
elseif(REQUIRE_FRONTENDS)
  message(FATAL_ERROR "Native package lacks frontend build information")
endif()
set(manuals pump pump-fast)
set(has_manuals FALSE)
foreach(frontend datapump-gui datapump-tui datapump-fb)
  if(EXISTS "${PACKAGE_ROOT}/bin/${frontend}" OR EXISTS "${PACKAGE_ROOT}/bin/${frontend}.exe")
    list(APPEND manuals ${frontend})
  endif()
endforeach()
foreach(manual IN LISTS manuals)
  if("share/man/man1/${manual}.1" IN_LIST recorded)
    set(has_manuals TRUE)
  endif()
endforeach()
if(REQUIRE_MANUALS OR has_manuals)
  foreach(manual IN LISTS manuals)
    if(NOT "share/man/man1/${manual}.1" IN_LIST recorded)
      message(FATAL_ERROR "Native package lacks the ${manual}(1) manual")
    endif()
  endforeach()
else()
  # Certification also checks releases produced before manuals were shipped.
  # New build/package callers opt in; a partial set is never accepted.
  message(STATUS "Historical native package has no installed man pages")
endif()
if(VERIFY_ONLY)
  message(STATUS "Native package inventory verified")
  return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/RuntimePolicy.cmake")
if(DEFINED BUILD_DIR AND EXISTS "${BUILD_DIR}/datapump-runtime-tool.cmake")
  include("${BUILD_DIR}/datapump-runtime-tool.cmake")
endif()
set(extension "")
if(WIN32)
  set(extension ".exe")
endif()
set(pump "${PACKAGE_ROOT}/bin/pump${extension}")
set(gui "${PACKAGE_ROOT}/bin/datapump-gui${extension}")
set(executables "${pump}")
if(EXISTS "${gui}")
  list(APPEND executables "${gui}")
endif()
foreach(frontend datapump-tui datapump-fb)
  if(EXISTS "${PACKAGE_ROOT}/bin/${frontend}${extension}")
    list(APPEND executables "${PACKAGE_ROOT}/bin/${frontend}${extension}")
  endif()
endforeach()
file(GLOB extra_roots "${PACKAGE_ROOT}/lib/libasound.so*")
file(GET_RUNTIME_DEPENDENCIES EXECUTABLES ${executables} LIBRARIES ${extra_roots}
  PRE_EXCLUDE_REGEXES ${DATAPUMP_OS_LIBRARIES}
  RESOLVED_DEPENDENCIES_VAR dependencies UNRESOLVED_DEPENDENCIES_VAR missing
  CONFLICTING_DEPENDENCIES_PREFIX conflicts)
if(missing OR conflicts_FILENAMES)
  message(FATAL_ERROR "Relocated package has unresolved/conflicting native dependencies: ${missing}; ${conflicts_FILENAMES}")
endif()
foreach(dependency IN LISTS dependencies)
  string(TOLOWER "${dependency}" dependency_name)
  if(dependency_name MATCHES "[/\\\\](lib)?lzma[^/\\\\]*\\.(so|dll|dylib)")
    message(FATAL_ERROR "Compression must be linked from pinned static sources: ${dependency}")
  endif()
  file(REAL_PATH "${dependency}" actual)
  set(prefix "${PACKAGE_ROOT}")
  if(WIN32)
    string(TOLOWER "${actual}" actual)
    string(TOLOWER "${prefix}" prefix)
  endif()
  cmake_path(IS_PREFIX prefix "${actual}" NORMALIZE inside)
  if(NOT inside)
    message(FATAL_ERROR "Relocated application depends on a host library: ${dependency}")
  endif()
endforeach()
set(isolated_environment "PATH=" "PYTHONHOME=/nonexistent" "PYTHONPATH=/nonexistent")
if(NOT WIN32)
  list(APPEND isolated_environment "LD_LIBRARY_PATH=")
endif()
function(check_command command_timeout)
  if(ARGV1 STREQUAL gui AND ARGV2 STREQUAL "--smoke-test" AND
      NOT "$ENV{DATAPUMP_CI_SMOKE_WARNINGS_DIR}" STREQUAL "" AND
      NOT "$ENV{DATAPUMP_CI_SMOKE_RUNNER}" STREQUAL "")
    set(smoke_wrapped TRUE)
    # The host runner classifies only the typed, advancing-work budget result.
    # Launch Python before clearing the copied application's runtime paths.
    set(smoke_runner "$ENV{DATAPUMP_CI_SMOKE_RUNNER}")
    if(NOT IS_ABSOLUTE "${smoke_runner}" OR NOT EXISTS "${smoke_runner}" OR
        IS_DIRECTORY "${smoke_runner}")
      message(FATAL_ERROR "DATAPUMP_CI_SMOKE_RUNNER must name an existing absolute file")
    endif()
    find_program(smoke_python NAMES python3 python NO_CMAKE_FIND_ROOT_PATH REQUIRED)
    get_filename_component(smoke_directory "$ENV{DATAPUMP_CI_SMOKE_WARNINGS_DIR}" ABSOLUTE)
    file(MAKE_DIRECTORY "${smoke_directory}")
    get_filename_component(smoke_name "${PACKAGE_ROOT}" NAME)
    if(DEFINED GUI_SMOKE_ARCHIVE_NAME)
      set(smoke_name "${GUI_SMOKE_ARCHIVE_NAME}")
    endif()
    string(REGEX REPLACE "[^A-Za-z0-9_.-]" "_" smoke_name "${smoke_name}")
    string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef smoke_identifier)
    set(smoke_evidence "${smoke_directory}/${smoke_name}-${smoke_identifier}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=PYTHONHOME --unset=PYTHONPATH
      "${smoke_python}" "${smoke_runner}" --allow-budget-exhaustion
      --log "${smoke_evidence}.log" --report "${smoke_evidence}.json" --
      "${CMAKE_COMMAND}" -E env ${isolated_environment} ${ARGN}
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT "${command_timeout}")
    # This includes incomplete-coverage warnings; their full output and typed
    # report remain in the caller's per-job artifact directory.
    if(NOT output STREQUAL "")
      message("${output}")
    endif()
    if(status EQUAL 0)
      if(NOT EXISTS "${smoke_evidence}.json")
        message(FATAL_ERROR "Native GUI smoke runner did not retain its required report")
      endif()
      file(READ "${smoke_evidence}.json" smoke_report)
      string(JSON smoke_status ERROR_VARIABLE report_error GET "${smoke_report}" status)
      if(report_error OR NOT smoke_status MATCHES "^(passed|incomplete)$")
        message(FATAL_ERROR "Native GUI smoke runner returned an invalid success report")
      endif()
      if(smoke_status STREQUAL "incomplete")
        set(package_gui_smoke_incomplete TRUE PARENT_SCOPE)
      endif()
    endif()
  else()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${isolated_environment} ${ARGN}
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT "${command_timeout}")
  endif()
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Relocated native command failed: ${ARGN}\n${output}\n${error}")
  endif()
  # Successful Rev smoke checks may still report display-cadence warnings.
  # Preserve them in CI logs instead of hiding captured stderr on success.
  if(NOT smoke_wrapped)
    string(REGEX MATCHALL "WARNING REV_REPLAY_CADENCE:[^\r\n]*" warnings "${output}\n${error}")
    foreach(warning IN LISTS warnings)
      message(STATUS "${warning}")
    endforeach()
  endif()
  set(command_output "${output}" PARENT_SCOPE)
endfunction()
check_command(120 "${pump}" --version)
check_command(120 "${pump}" simulate --text "offline native relocation" --snr 18 --json)
string(JSON validated ERROR_VARIABLE json_error GET "${command_output}" validated)
if(json_error OR NOT validated)
  message(FATAL_ERROR "Relocated modem simulation did not return validated content: ${command_output}")
endif()
# Exercise the long codec inside the copied executable with no runtime tools
# or package paths, in addition to the short-message simulation above.
string(REPEAT "portable compressed data pump content " 64 long_text)
check_command(120 "${pump}" simulate --text "${long_text}" --snr 18 --json)
string(JSON validated ERROR_VARIABLE json_error GET "${command_output}" validated)
if(json_error OR NOT validated)
  message(FATAL_ERROR "Relocated long-payload codec failed: ${command_output}")
endif()
if(EXISTS "${gui}")
  check_command(120 "${gui}" --self-check)
  if(GUI_SMOKE)
    if(DEFINED GUI_SMOKE_TIMEOUT)
      check_command("${GUI_SMOKE_PROCESS_TIMEOUT}" "${gui}" --smoke-test
        --smoke-timeout "${GUI_SMOKE_TIMEOUT}")
    else()
      check_command(120 "${gui}" --smoke-test)
    endif()
  endif()
endif()
foreach(frontend datapump-tui datapump-fb)
  if(EXISTS "${PACKAGE_ROOT}/bin/${frontend}${extension}")
    check_command(120 "${PACKAGE_ROOT}/bin/${frontend}${extension}" --self-check)
  endif()
endforeach()
if(EXISTS "${PACKAGE_ROOT}/bin/datapump-fb${extension}")
  check_command(30 "${PACKAGE_ROOT}/bin/datapump-fb${extension}" --simulation --headless --frames 3)
  check_command(30 "${CMAKE_COMMAND}" -E env SDL_VIDEODRIVER=dummy
    "${PACKAGE_ROOT}/bin/datapump-fb${extension}" --simulation --frames 3)
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND NOT "$ENV{DISPLAY}" STREQUAL "")
    # Exercise the copied software host itself; FLTK/Rev success cannot prove
    # SDL's X11 dependencies are present in the relocated closure.
    check_command(30 "${CMAKE_COMMAND}" -E env SDL_VIDEODRIVER=x11
      "${PACKAGE_ROOT}/bin/datapump-fb${extension}" --simulation --frames 3)
  endif()
endif()
if(package_gui_smoke_incomplete)
  message(STATUS "Native package inventory and dependency closure verified; GUI smoke coverage incomplete (see retained warning report)")
else()
  message(STATUS "Native package inventory, dependency closure, and isolated commands verified")
endif()
