# Use the same verifier for local CPack output and freshly downloaded CI artifacts.
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/gui-smoke-timeout.cmake")
set(gui_smoke_options "")
if(DEFINED GUI_SMOKE_TIMEOUT)
  list(APPEND gui_smoke_options "-DGUI_SMOKE_TIMEOUT=${GUI_SMOKE_TIMEOUT}")
endif()
if(NOT DEFINED ARCHIVE_DIR)
  message(FATAL_ERROR "Provide -DARCHIVE_DIR=/path/to/native/archives")
endif()
get_filename_component(ARCHIVE_DIR "${ARCHIVE_DIR}" ABSOLUTE)
file(GLOB tarballs "${ARCHIVE_DIR}/DataPump-*-native.tar.gz"
  "${ARCHIVE_DIR}/DataPump-*-native-fltk.tar.gz" "${ARCHIVE_DIR}/DataPump-*-native-rev.tar.gz")
file(GLOB zipfiles "${ARCHIVE_DIR}/DataPump-*-native.zip"
  "${ARCHIVE_DIR}/DataPump-*-native-fltk.zip" "${ARCHIVE_DIR}/DataPump-*-native-rev.zip")
if(NOT tarballs OR NOT zipfiles)
  message(FATAL_ERROR "Both native TGZ and ZIP archives must be present")
endif()
set(archives ${tarballs} ${zipfiles})
list(SORT archives)
foreach(tarball IN LISTS tarballs)
  string(REGEX REPLACE "\\.tar\\.gz$" ".zip" paired "${tarball}")
  if(NOT paired IN_LIST zipfiles)
    message(FATAL_ERROR "Missing ZIP companion for ${tarball}")
  endif()
endforeach()
foreach(zipfile IN LISTS zipfiles)
  string(REGEX REPLACE "\\.zip$" ".tar.gz" paired "${zipfile}")
  if(NOT paired IN_LIST tarballs)
    message(FATAL_ERROR "Missing TGZ companion for ${zipfile}")
  endif()
endforeach()
set(checksums "")
foreach(archive IN LISTS archives)
  get_filename_component(filename "${archive}" NAME)
  file(SHA256 "${archive}" digest)
  string(APPEND checksums "${digest}  ${filename}\n")
endforeach()
# Validate a downloaded archive inventory before extracting or executing it.
if(EXISTS "${ARCHIVE_DIR}/SHA256SUMS.txt")
  file(READ "${ARCHIVE_DIR}/SHA256SUMS.txt" expected)
  if(NOT checksums STREQUAL expected)
    message(FATAL_ERROR "Native archive checksums differ from SHA256SUMS.txt")
  endif()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identifier)
set(scratch "${ARCHIVE_DIR}/verification-${identifier}")
file(MAKE_DIRECTORY "${scratch}")
foreach(archive IN LISTS archives)
  get_filename_component(filename "${archive}" NAME)
  set(destination "${scratch}/${filename}/offline destination with spaces")
  file(MAKE_DIRECTORY "${destination}")
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${destination}")
  file(GLOB manifests "${destination}/*/manifest.sha256")
  list(LENGTH manifests manifest_count)
  if(NOT manifest_count EQUAL 1)
    message(FATAL_ERROR "${filename} must contain one complete native installation")
  endif()
  list(GET manifests 0 manifest)
  get_filename_component(package_root "${manifest}" DIRECTORY)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${package_root}"
    "-DBUILD_DIR=${BUILD_DIR}" "-DGUI_SMOKE=${GUI_SMOKE}" ${gui_smoke_options}
    -P "${CMAKE_CURRENT_LIST_DIR}/verify-native-package.cmake"
    RESULT_VARIABLE verified)
  if(NOT verified EQUAL 0)
    message(FATAL_ERROR "Native archive verification failed: ${filename}")
  endif()
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(abi_options "")
    if(DEFINED MAX_GLIBC)
      list(APPEND abi_options "-DMAX_GLIBC=${MAX_GLIBC}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${package_root}"
      ${abi_options} -P "${CMAKE_CURRENT_LIST_DIR}/verify-linux-abi.cmake"
      RESULT_VARIABLE verified)
    if(NOT verified EQUAL 0)
      message(FATAL_ERROR "Linux archive ABI verification failed: ${filename}")
    endif()
  endif()
endforeach()
if(NOT EXISTS "${ARCHIVE_DIR}/SHA256SUMS.txt")
  file(WRITE "${ARCHIVE_DIR}/SHA256SUMS.txt" "${checksums}")
endif()
message(STATUS "Both native archive formats verified in ${scratch}")
