# Audit every shipped ELF, including indirect dependencies. GLib is the GNOME
# utility library; glibc is the Linux C runtime and has a separate ABI ceiling.
cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED PACKAGE_ROOT)
  message(FATAL_ERROR "Provide -DPACKAGE_ROOT=/path/to/installed/DataPump")
endif()
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "The ELF/glibc audit must run on Linux")
endif()
if(DEFINED MAX_GLIBC AND NOT MAX_GLIBC MATCHES "^[0-9]+(\\.[0-9]+)+$")
  message(FATAL_ERROR "MAX_GLIBC must be a numeric ABI version such as 2.35")
endif()
find_program(readelf NAMES readelf REQUIRED)
file(GLOB_RECURSE candidates LIST_DIRECTORIES FALSE "${PACKAGE_ROOT}/bin/*" "${PACKAGE_ROOT}/lib/*")
set(highest_glibc "0")
set(elf_count 0)
foreach(candidate IN LISTS candidates)
  get_filename_component(name "${candidate}" NAME)
  if(name MATCHES "^lib(glib|gobject|gmodule|gthread|gio)-2\\.0\\.so" OR
      name MATCHES "^lib(gtk|gdk)(-|\\.)")
    message(FATAL_ERROR "Portable FLTK application unexpectedly includes GTK/GLib: ${name}")
  endif()
  file(READ "${candidate}" magic LIMIT 4 HEX)
  if(NOT magic STREQUAL "7f454c46")
    continue()
  endif()
  math(EXPR elf_count "${elf_count} + 1")
  execute_process(COMMAND "${readelf}" --version-info --wide "${candidate}"
    RESULT_VARIABLE status OUTPUT_VARIABLE versions ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ELF ABI for ${candidate}: ${error}")
  endif()
  # Named ABI additions also raise the runtime baseline and cannot safely be
  # treated as an old numeric version (for example packed relative relocations).
  if(DEFINED MAX_GLIBC AND versions MATCHES "GLIBC_(ABI_[A-Za-z0-9_]+|PRIVATE)")
    message(FATAL_ERROR "${name} uses ${CMAKE_MATCH_0}, outside the declared glibc ${MAX_GLIBC} baseline")
  endif()
  string(REGEX MATCHALL "GLIBC_[0-9]+(\\.[0-9]+)+" requirements "${versions}")
  list(REMOVE_DUPLICATES requirements)
  foreach(requirement IN LISTS requirements)
    string(REPLACE "GLIBC_" "" version "${requirement}")
    if(DEFINED MAX_GLIBC AND version VERSION_GREATER MAX_GLIBC)
      message(FATAL_ERROR "${name} requires glibc ${version}, newer than the ${MAX_GLIBC} baseline")
    endif()
    if(version VERSION_GREATER highest_glibc)
      set(highest_glibc "${version}")
    endif()
  endforeach()
endforeach()
if(elf_count EQUAL 0)
  message(FATAL_ERROR "No packaged ELF binaries found")
endif()
message(STATUS "${elf_count} packaged ELF files: no GTK/GLib; highest numeric glibc requirement ${highest_glibc}")
