# Rev is an opt-in C++23 module backend. Keep its toolchain/dependencies local to
# this selection; ordinary FLTK and CLI builds retain the C++20 baseline.
if(CMAKE_VERSION VERSION_LESS 3.28)
  message(FATAL_ERROR "The Rev backend requires CMake 3.28 or newer (C++ modules).")
endif()
if(NOT CMAKE_GENERATOR MATCHES "Ninja|Visual Studio")
  message(FATAL_ERROR "The Rev backend requires a Ninja or Visual Studio generator for C++ modules.")
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 15)
  message(FATAL_ERROR "This pinned Rev revision triggers a GCC 14 module compiler error. Use the source SDK's GCC 15.3, or configure a fresh Ninja build with -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_C_COMPILER=clang-19 (or a newer compiler). FLTK and CLI builds do not require this toolchain.")
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19)
  message(FATAL_ERROR "The Rev backend requires Clang 19 or newer for its C++23 modules.")
endif()
if(NOT CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|MSVC|AppleClang)$")
  message(FATAL_ERROR "The Rev backend needs a compiler supported by CMake C++ modules; use Clang 19+ with Ninja.")
endif()
if(APPLE)
  message(FATAL_ERROR "The Rev adapter currently supports Linux/X11 and Windows/OpenGL. The upstream Metal path has not been integrated yet.")
elseif(WIN32)
  set(datapump_rev_platform win)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(datapump_rev_platform lnx)
else()
  message(FATAL_ERROR "The Rev adapter currently supports Linux/X11 and Windows/OpenGL only.")
endif()
find_package(Python3 REQUIRED COMPONENTS Interpreter)
find_package(OpenGL REQUIRED)
find_package(GLEW REQUIRED)
find_package(Freetype REQUIRED)
if(UNIX)
  find_package(X11 REQUIRED COMPONENTS Xrandr Xext)
endif()
set(datapump_rev_root "${CMAKE_CURRENT_SOURCE_DIR}/third_party/rev")
set(datapump_rev_generated "${CMAKE_CURRENT_BINARY_DIR}/rev-generated")
file(GLOB_RECURSE datapump_rev_inputs CONFIGURE_DEPENDS
  "${datapump_rev_root}/source/*" "${datapump_rev_root}/resources/*")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/tools/prepare_rev.py" ${datapump_rev_inputs})
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tools/prepare_rev.py"
  --source "${datapump_rev_root}" --output "${datapump_rev_generated}"
  --platform "${datapump_rev_platform}" COMMAND_ERROR_IS_FATAL ANY)
include("${datapump_rev_generated}/modules.cmake")
add_library(datapump_rev STATIC "${datapump_rev_generated}/rev_embedded.cpp")
set_target_properties(datapump_rev PROPERTIES CXX_STANDARD 23 CXX_SCAN_FOR_MODULES ON)
target_sources(datapump_rev PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES
  BASE_DIRS "${datapump_rev_generated}" FILES ${DATAPUMP_REV_MODULES})
target_include_directories(datapump_rev PUBLIC
  "${datapump_rev_root}/external" "${datapump_rev_root}/source/OS/Window"
  "${datapump_rev_generated}")
target_compile_definitions(datapump_rev PRIVATE PROJECT_ROOT="${datapump_rev_root}")
target_compile_definitions(datapump_rev PUBLIC PLATFORM_OPENGL)
target_link_libraries(datapump_rev PUBLIC OpenGL::GL GLEW::GLEW Freetype::Freetype)
if(WIN32)
  target_link_libraries(datapump_rev PUBLIC user32 gdi32 ole32 shell32 uuid dwmapi shcore setupapi)
else()
  target_link_libraries(datapump_rev PUBLIC X11::X11 X11::Xrandr X11::Xext)
endif()
add_executable(datapump-gui WIN32 src/gui/backend_rev.cpp src/gui/rev_platform.cpp)
if(WIN32)
  target_sources(datapump-gui PRIVATE src/gui/rev_entry_win.cpp)
endif()
set_target_properties(datapump-gui PROPERTIES CXX_STANDARD 23 CXX_SCAN_FOR_MODULES ON)
target_link_libraries(datapump-gui PRIVATE datapump_rev)
install(FILES third_party/rev/README.datapump.md third_party/rev/UPSTREAM.json
  DESTINATION share/doc/datapump/rev)
install(FILES third_party/rev/resources/DejaVu-LICENSE DESTINATION share/doc/datapump/rev)

install(FILES third_party/rev/external/glm/LICENSE DESTINATION share/doc/datapump/rev RENAME GLM-LICENSE)
install(FILES third_party/rev/external/nanosvg/LICENSE DESTINATION share/doc/datapump/rev RENAME NANOSVG-LICENSE)
