include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/StaticCxxRuntime.cmake")
set(DATAPUMP_RUNTIME_DIRS "" CACHE STRING "Additional existing native-library search directories")
set(DATAPUMP_EXTRA_LICENSES "" CACHE STRING "Local runtime license/notice files to include")

function(datapump_install_native)
  cmake_parse_arguments(PACKAGE "" "" "TARGETS" ${ARGN})
  if(NOT PACKAGE_TARGETS)
    message(FATAL_ERROR "datapump_install_native requires TARGETS")
  endif()
  set(DATAPUMP_PACKAGE_SDK_ROOT "")
  set(DATAPUMP_PACKAGE_SYSROOT "")
  set(DATAPUMP_SDK_RUNTIME_HELPER "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/SdkRuntime.cmake")
  if(DATAPUMP_SDK_ROOT)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT IS_ABSOLUTE "${CMAKE_SYSROOT}"
        OR NOT IS_DIRECTORY "${CMAKE_SYSROOT}")
      message(FATAL_ERROR "SDK packaging requires Linux and an existing absolute CMAKE_SYSROOT")
    endif()
    file(REAL_PATH "${DATAPUMP_SDK_ROOT}" DATAPUMP_PACKAGE_SDK_ROOT)
    file(REAL_PATH "${CMAKE_SYSROOT}" DATAPUMP_PACKAGE_SYSROOT)
    include("${DATAPUMP_SDK_RUNTIME_HELPER}")
    datapump_sdk_validate_path("${DATAPUMP_PACKAGE_SYSROOT}" "${DATAPUMP_PACKAGE_SDK_ROOT}")
  endif()
  set(DATAPUMP_EXECUTABLE_NAMES "")
  set(DATAPUMP_SEARCH_DIRS "${DATAPUMP_RUNTIME_DIRS}")
  set(DATAPUMP_NOTICE_INPUTS "${OPENSSL_CRYPTO_LIBRARY}")
  set(DATAPUMP_SDK_EXTERNAL_LIBRARIES "")
  if(DATAPUMP_SDK_ROOT)
    # Find-root modes do not reject explicit/cache-provided paths. Static
    # archives disappear from DT_NEEDED, so guard them before linking too.
    foreach(source IN LISTS OPENSSL_CRYPTO_LIBRARY)
      if(source STREQUAL "optimized" OR source STREQUAL "debug" OR source STREQUAL "general")
        continue()
      endif()
      if(NOT IS_ABSOLUTE "${source}")
        message(FATAL_ERROR "SDK external library must have an absolute path: ${source}")
      endif()
      datapump_sdk_validate_path("${source}" "${DATAPUMP_PACKAGE_SYSROOT}")
      list(APPEND DATAPUMP_SDK_EXTERNAL_LIBRARIES "${source}")
    endforeach()
    foreach(external_target OpenSSL::Crypto ZLIB::ZLIB)
      if(NOT TARGET "${external_target}")
        continue()
      endif()
      get_target_property(imported "${external_target}" IMPORTED)
      if(NOT imported)
        # A vendored/build-produced target belongs to this application build.
        continue()
      endif()
      get_property(configurations TARGET "${external_target}" PROPERTY IMPORTED_CONFIGURATIONS)
      list(APPEND configurations ${CMAKE_CONFIGURATION_TYPES} "${CMAKE_BUILD_TYPE}"
        DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
      list(REMOVE_DUPLICATES configurations)
      set(location_properties IMPORTED_LOCATION)
      foreach(configuration IN LISTS configurations)
        string(TOUPPER "${configuration}" configuration)
        list(APPEND location_properties "IMPORTED_LOCATION_${configuration}")
      endforeach()
      foreach(property IN LISTS location_properties)
        get_target_property(source "${external_target}" "${property}")
        if(source)
          if(NOT IS_ABSOLUTE "${source}")
            message(FATAL_ERROR "SDK external library must have an absolute path: ${external_target} -> ${source}")
          endif()
          datapump_sdk_validate_path("${source}" "${DATAPUMP_PACKAGE_SYSROOT}")
        endif()
      endforeach()
      # Check the selected configuration again at packaging time, including
      # symlinks or inputs changed after configuration.
      list(APPEND DATAPUMP_SDK_EXTERNAL_LIBRARIES "$<TARGET_FILE:${external_target}>")
    endforeach()
  endif()
  if(TARGET ZLIB::ZLIB)
    list(APPEND DATAPUMP_NOTICE_INPUTS "$<TARGET_FILE:ZLIB::ZLIB>")
  endif()
  if(NOT DATAPUMP_SDK_ROOT AND DATAPUMP_STATIC_GNU_RUNTIME)
    foreach(archive libstdc++.a libgcc.a libgcc_eh.a)
      execute_process(COMMAND "${CMAKE_CXX_COMPILER}" "-print-file-name=${archive}"
        OUTPUT_VARIABLE archive_path OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(EXISTS "${archive_path}")
        list(APPEND DATAPUMP_NOTICE_INPUTS "${archive_path}")
      endif()
    endforeach()
  endif()
  set(DATAPUMP_NOTICE_FILES "${DATAPUMP_EXTRA_LICENSES}")
  if(NOT DATAPUMP_SDK_ROOT)
    foreach(candidate
      "${OPENSSL_INCLUDE_DIR}/../share/openssl/copyright"
      "${OPENSSL_ROOT_DIR}/share/openssl/copyright"
      "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/openssl/copyright"
      "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/openssl/copyright"
      "/usr/share/licenses/openssl-libs/LICENSE.txt")
      if(EXISTS "${candidate}")
        list(APPEND DATAPUMP_NOTICE_FILES "${candidate}")
        break()
      endif()
    endforeach()
    if(TARGET datapump_rev)
      # Static vcpkg libraries do not appear in the runtime dependency scan.
      # Use their complete port notices for the selected Rev backend only.
      foreach(port glew freetype)
        foreach(prefix "${VCPKG_INSTALLED_DIR}" "${_VCPKG_INSTALLED_DIR}")
          set(candidate "${prefix}/${VCPKG_TARGET_TRIPLET}/share/${port}/copyright")
          if(prefix AND EXISTS "${candidate}")
            list(APPEND DATAPUMP_NOTICE_FILES "${candidate}")
            break()
          endif()
        endforeach()
      endforeach()
    endif()
  endif()
  foreach(target IN LISTS PACKAGE_TARGETS)
    if(DATAPUMP_PORTABLE AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
      set_target_properties(${target} PROPERTIES
        INSTALL_RPATH "$ORIGIN/../lib" INSTALL_RPATH_USE_LINK_PATH FALSE)
      # Inherited RPATH also resolves the dependencies of the copied X11 libs.
      target_link_options(${target} PRIVATE "LINKER:--disable-new-dtags")
    endif()
    list(APPEND DATAPUMP_EXECUTABLE_NAMES "$<TARGET_FILE_NAME:${target}>")
    list(APPEND DATAPUMP_SEARCH_DIRS "$<TARGET_FILE_DIR:${target}>")
  endforeach()
  install(TARGETS ${PACKAGE_TARGETS} RUNTIME DESTINATION bin)
  if(NOT DATAPUMP_PORTABLE)
    return()
  endif()
  if(NOT WIN32 AND NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Portable native packaging currently supports Linux and Windows")
  endif()
  set(DATAPUMP_RUNTIME_TOOL "objdump")
  set(DATAPUMP_RUNTIME_COMMAND "${CMAKE_OBJDUMP}")
  if(MSVC)
    get_filename_component(linker_directory "${CMAKE_LINKER}" DIRECTORY)
    find_program(DATAPUMP_DUMPBIN dumpbin HINTS "${linker_directory}")
    set(DATAPUMP_RUNTIME_TOOL "dumpbin")
    set(DATAPUMP_RUNTIME_COMMAND "${DATAPUMP_DUMPBIN}")
  endif()
  if(NOT DATAPUMP_RUNTIME_COMMAND OR NOT EXISTS "${DATAPUMP_RUNTIME_COMMAND}")
    message(FATAL_ERROR "Portable packaging needs the toolchain's local objdump or dumpbin")
  endif()
  if(WIN32)
    set(DATAPUMP_RUNTIME_PLATFORM "windows+pe")
  else()
    set(DATAPUMP_RUNTIME_PLATFORM "linux+elf")
    if(DATAPUMP_SDK_ROOT)
      # Do not reuse find_library's cache or an implicit host linker directory.
      datapump_sdk_find_library("libasound.so.2" "${DATAPUMP_PACKAGE_SYSROOT}" DATAPUMP_ALSA_LIBRARY)
    else()
      find_library(DATAPUMP_ALSA_LIBRARY NAMES asound libasound.so.2
        PATHS ${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES})
    endif()
    if(DATAPUMP_ALSA_LIBRARY MATCHES "\\.a$")
      set(DATAPUMP_ALSA_LIBRARY "")
    endif()
    if(NOT DATAPUMP_ALSA_LIBRARY)
      message(STATUS "No local ALSA shared library: portable WAV/simulation work; live audio needs host ALSA")
    endif()
  endif()
  set(DATAPUMP_POLICY_FILE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RuntimePolicy.cmake")
  set(DATAPUMP_PACKAGE_TEMPLATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/package-native.cmake")
  configure_file("${DATAPUMP_PACKAGE_TEMPLATE}"
    "${CMAKE_CURRENT_BINARY_DIR}/package-native-configured.cmake" @ONLY)
  file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/package-native-$<CONFIG>.cmake"
    INPUT "${CMAKE_CURRENT_BINARY_DIR}/package-native-configured.cmake")
  install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/package-native-$<CONFIG>.cmake")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/datapump-runtime-tool.cmake"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM [==[${DATAPUMP_RUNTIME_PLATFORM}]==])\n"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL [==[${DATAPUMP_RUNTIME_TOOL}]==])\n"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND [==[${DATAPUMP_RUNTIME_COMMAND}]==])\n")
endfunction()
