include_guard(GLOBAL)
set(DATAPUMP_RUNTIME_DIRS "" CACHE STRING "Additional existing native-library search directories")
set(DATAPUMP_EXTRA_LICENSES "" CACHE STRING "Local runtime license/notice files to include")

function(datapump_install_native)
  cmake_parse_arguments(PACKAGE "" "" "TARGETS" ${ARGN})
  if(NOT PACKAGE_TARGETS)
    message(FATAL_ERROR "datapump_install_native requires TARGETS")
  endif()
  set(DATAPUMP_EXECUTABLE_NAMES "")
  set(DATAPUMP_SEARCH_DIRS "${DATAPUMP_RUNTIME_DIRS}")
  set(DATAPUMP_NOTICE_INPUTS "${OPENSSL_CRYPTO_LIBRARY}")
  if(TARGET ZLIB::ZLIB)
    list(APPEND DATAPUMP_NOTICE_INPUTS "$<TARGET_FILE:ZLIB::ZLIB>")
  endif()
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND NOT DATAPUMP_SANITIZERS)
    foreach(archive libstdc++.a libgcc.a)
      execute_process(COMMAND "${CMAKE_CXX_COMPILER}" "-print-file-name=${archive}"
        OUTPUT_VARIABLE archive_path OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(EXISTS "${archive_path}")
        list(APPEND DATAPUMP_NOTICE_INPUTS "${archive_path}")
      endif()
    endforeach()
  endif()
  set(DATAPUMP_NOTICE_FILES "${DATAPUMP_EXTRA_LICENSES}")
  foreach(candidate
      "${OPENSSL_INCLUDE_DIR}/../share/openssl/copyright"
      "${OPENSSL_ROOT_DIR}/share/openssl/copyright"
      "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/openssl/copyright"
      "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/openssl/copyright"
      "/usr/share/licenses/openssl-libs/LICENSE.txt")
    if(EXISTS "${candidate}")
      list(APPEND DATAPUMP_NOTICE_FILES "${candidate}")
      break()
    endif()
  endforeach()
  foreach(target IN LISTS PACKAGE_TARGETS)
    if(DATAPUMP_PORTABLE AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
      set_target_properties(${target} PROPERTIES
        INSTALL_RPATH "$ORIGIN/../lib" INSTALL_RPATH_USE_LINK_PATH FALSE)
      # Inherited RPATH also resolves the dependencies of the copied X11 libs.
      target_link_options(${target} PRIVATE "LINKER:--disable-new-dtags")
    endif()
    list(APPEND DATAPUMP_EXECUTABLE_NAMES "$<TARGET_FILE_NAME:${target}>")
    list(APPEND DATAPUMP_SEARCH_DIRS "$<TARGET_FILE_DIR:${target}>")
  endforeach()
  install(TARGETS ${PACKAGE_TARGETS} RUNTIME DESTINATION bin)
  if(NOT DATAPUMP_PORTABLE)
    return()
  endif()
  if(NOT WIN32 AND NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Portable native packaging currently supports Linux and Windows")
  endif()
  set(DATAPUMP_RUNTIME_TOOL "objdump")
  set(DATAPUMP_RUNTIME_COMMAND "${CMAKE_OBJDUMP}")
  if(MSVC)
    get_filename_component(linker_directory "${CMAKE_LINKER}" DIRECTORY)
    find_program(DATAPUMP_DUMPBIN dumpbin HINTS "${linker_directory}")
    set(DATAPUMP_RUNTIME_TOOL "dumpbin")
    set(DATAPUMP_RUNTIME_COMMAND "${DATAPUMP_DUMPBIN}")
  endif()
  if(NOT DATAPUMP_RUNTIME_COMMAND OR NOT EXISTS "${DATAPUMP_RUNTIME_COMMAND}")
    message(FATAL_ERROR "Portable packaging needs the toolchain's local objdump or dumpbin")
  endif()
  if(WIN32)
    set(DATAPUMP_RUNTIME_PLATFORM "windows+pe")
  else()
    set(DATAPUMP_RUNTIME_PLATFORM "linux+elf")
    find_library(DATAPUMP_ALSA_LIBRARY NAMES asound libasound.so.2
      PATHS ${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES})
    if(DATAPUMP_ALSA_LIBRARY MATCHES "\\.a$")
      set(DATAPUMP_ALSA_LIBRARY "")
    endif()
    if(NOT DATAPUMP_ALSA_LIBRARY)
      message(STATUS "No local ALSA shared library: portable WAV/simulation work; live audio needs host ALSA")
    endif()
  endif()
  set(DATAPUMP_POLICY_FILE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RuntimePolicy.cmake")
  set(DATAPUMP_PACKAGE_TEMPLATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/package-native.cmake")
  configure_file("${DATAPUMP_PACKAGE_TEMPLATE}"
    "${CMAKE_CURRENT_BINARY_DIR}/package-native-configured.cmake" @ONLY)
  file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/package-native-$<CONFIG>.cmake"
    INPUT "${CMAKE_CURRENT_BINARY_DIR}/package-native-configured.cmake")
  install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/package-native-$<CONFIG>.cmake")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/datapump-runtime-tool.cmake"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM [==[${DATAPUMP_RUNTIME_PLATFORM}]==])\n"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL [==[${DATAPUMP_RUNTIME_TOOL}]==])\n"
    "set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND [==[${DATAPUMP_RUNTIME_COMMAND}]==])\n")
endfunction()
