# Independent interactive frontends share the same application boundary.
# Their presentation and interaction implementations are
# separate. Neither terminal nor framebuffer selection changes the
# FLTK/Rev choice, and embedding the CPU renderer needs no window toolkit.
if(NOT DATAPUMP_BUILD_TUI AND NOT DATAPUMP_BUILD_FB AND NOT DATAPUMP_BUILD_FRAMEBUFFER_LIBRARY AND NOT BUILD_TESTING)
  return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/GuiShared.cmake")
add_library(datapump_terminal_ui STATIC EXCLUDE_FROM_ALL src/gui/terminal_ui.cpp)
target_include_directories(datapump_terminal_ui PUBLIC src/gui)
target_link_libraries(datapump_terminal_ui PUBLIC datapump_gui_application)
add_library(datapump_framebuffer STATIC EXCLUDE_FROM_ALL src/gui/framebuffer.cpp src/gui/framebuffer_ui.cpp)
target_include_directories(datapump_framebuffer PUBLIC src/gui)
target_link_libraries(datapump_framebuffer PUBLIC datapump_gui_application)
if(DATAPUMP_BUILD_FRAMEBUFFER_LIBRARY)
  set_property(TARGET datapump_framebuffer PROPERTY EXCLUDE_FROM_ALL FALSE)
endif()
if(DATAPUMP_BUILD_FB OR DATAPUMP_BUILD_FRAMEBUFFER_LIBRARY)
  # The committed glyph atlas needs its notice even when Rev is not built.
  install(FILES third_party/rev/resources/DejaVu-LICENSE
    DESTINATION share/doc/datapump/framebuffer)
endif()
foreach(target datapump_terminal_ui datapump_framebuffer)
  target_compile_features(${target} PUBLIC cxx_std_20)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive-)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  endif()
endforeach()

if(DATAPUMP_BUILD_TUI)
  if(DATAPUMP_TUI_BACKEND STREQUAL "auto")
    if(WIN32)
      set(DATAPUMP_TUI_BACKEND winconsole)
    else()
      set(DATAPUMP_TUI_BACKEND ncurses)
    endif()
  endif()
  if(DATAPUMP_TUI_BACKEND STREQUAL "ncurses" AND UNIX)
    set(CURSES_NEED_WIDE TRUE)
    set(CURSES_NEED_NCURSES TRUE)
    find_package(Curses REQUIRED)
    if(DATAPUMP_SDK_ROOT)
      include("${CMAKE_CURRENT_LIST_DIR}/SdkRuntime.cmake")
      foreach(path IN LISTS CURSES_INCLUDE_DIRS CURSES_LIBRARIES)
        datapump_sdk_validate_path("${path}" "${CMAKE_SYSROOT}")
      endforeach()
    endif()
    add_executable(datapump-tui src/gui/backend_ncurses.cpp)
    target_include_directories(datapump-tui PRIVATE ${CURSES_INCLUDE_DIRS})
    target_link_libraries(datapump-tui PRIVATE datapump_terminal_ui ${CURSES_LIBRARIES})
  elseif(DATAPUMP_TUI_BACKEND STREQUAL "winconsole" AND WIN32)
    add_executable(datapump-tui src/gui/backend_winconsole.cpp)
    target_link_libraries(datapump-tui PRIVATE datapump_terminal_ui)
  else()
    message(FATAL_ERROR "TUI adapter must be ncurses on POSIX or winconsole on Windows (auto selects it)")
  endif()
  list(APPEND datapump_executables datapump-tui)
endif()

if(DATAPUMP_BUILD_FB)
  if(NOT DATAPUMP_FB_HOST STREQUAL "sdl")
    message(FATAL_ERROR "Implemented framebuffer application hosts: sdl (SDL2)")
  endif()
  # Ordinary package/system discovery only; configuration never downloads or
  # silently builds dependencies. Explicit paths support prepared toolchains.
  find_package(SDL2 CONFIG QUIET)
  if(TARGET SDL2::SDL2-static AND WIN32)
    set(DATAPUMP_SDL2_TARGET SDL2::SDL2-static)
  elseif(TARGET SDL2::SDL2)
    set(DATAPUMP_SDL2_TARGET SDL2::SDL2)
  elseif(TARGET SDL2::SDL2-static)
    set(DATAPUMP_SDL2_TARGET SDL2::SDL2-static)
  else()
    find_path(SDL2_INCLUDE_DIR SDL.h PATH_SUFFIXES SDL2)
    find_library(SDL2_LIBRARY NAMES SDL2 SDL2-2.0)
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(SDL2 REQUIRED_VARS SDL2_INCLUDE_DIR SDL2_LIBRARY)
    if(NOT SDL2_FOUND)
      message(FATAL_ERROR "datapump-fb requires SDL2 development files; the embedding library does not")
    endif()
    add_library(datapump_sdl2 UNKNOWN IMPORTED)
    set_target_properties(datapump_sdl2 PROPERTIES IMPORTED_LOCATION "${SDL2_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}")
    set(DATAPUMP_SDL2_TARGET datapump_sdl2)
  endif()
  if(DATAPUMP_SDK_ROOT)
    include("${CMAKE_CURRENT_LIST_DIR}/SdkRuntime.cmake")
    get_target_property(sdl_includes ${DATAPUMP_SDL2_TARGET} INTERFACE_INCLUDE_DIRECTORIES)
    foreach(path IN LISTS sdl_includes)
      datapump_sdk_validate_path("${path}" "${CMAKE_SYSROOT}")
    endforeach()
    get_target_property(sdl_configs ${DATAPUMP_SDL2_TARGET} IMPORTED_CONFIGURATIONS)
    set(sdl_locations IMPORTED_LOCATION)
    foreach(config IN LISTS sdl_configs)
      list(APPEND sdl_locations "IMPORTED_LOCATION_${config}")
    endforeach()
    foreach(property IN LISTS sdl_locations)
      get_target_property(path ${DATAPUMP_SDL2_TARGET} ${property})
      if(path)
        datapump_sdk_validate_path("${path}" "${CMAKE_SYSROOT}")
      endif()
    endforeach()
  endif()
  add_executable(datapump-fb src/gui/backend_sdl.cpp)
  target_link_libraries(datapump-fb PRIVATE datapump_framebuffer ${DATAPUMP_SDL2_TARGET})
  if(DATAPUMP_DEPENDENCY_PREFIX AND CMAKE_LIBRARY_ARCHITECTURE AND
      IS_DIRECTORY "${DATAPUMP_DEPENDENCY_PREFIX}/include/${CMAKE_LIBRARY_ARCHITECTURE}")
    # Distribution SDL headers may forward to a private multiarch header.
    target_include_directories(datapump-fb PRIVATE
      "${DATAPUMP_DEPENDENCY_PREFIX}/include/${CMAKE_LIBRARY_ARCHITECTURE}")
  endif()
  list(APPEND datapump_executables datapump-fb)
endif()

if(MSVC)
  foreach(frontend datapump-tui datapump-fb)
    if(TARGET ${frontend})
      # All application entry points interpret narrow arguments as UTF-8.
      target_link_options(${frontend} PRIVATE "/MANIFEST:EMBED"
        "/MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/src/pump.manifest")
    endif()
  endforeach()
endif()

if(BUILD_TESTING)
  add_executable(test_terminal_ui tests/test_terminal_ui.cpp)
  target_link_libraries(test_terminal_ui PRIVATE datapump_terminal_ui)
  add_test(NAME terminal_ui COMMAND test_terminal_ui)
  add_executable(test_terminal_bitmap tests/test_terminal_bitmap.cpp)
  target_link_libraries(test_terminal_bitmap PRIVATE datapump_terminal_ui)
  add_test(NAME terminal_bitmap COMMAND test_terminal_bitmap)
  add_executable(test_framebuffer tests/test_framebuffer.cpp)
  target_link_libraries(test_framebuffer PRIVATE datapump_framebuffer datapump)
  add_test(NAME framebuffer COMMAND test_framebuffer)
  set_tests_properties(terminal_ui terminal_bitmap framebuffer PROPERTIES LABELS "frontends")
  if(DATAPUMP_BUILD_TUI)
    add_test(NAME tui_self_check COMMAND datapump-tui --self-check)
    set_tests_properties(tui_self_check PROPERTIES LABELS "frontends" TIMEOUT 300)
    find_package(Python3 COMPONENTS Interpreter QUIET)
    if(Python3_Interpreter_FOUND AND DATAPUMP_TUI_BACKEND STREQUAL "ncurses")
      add_executable(datapump_tui_adapter_test src/gui/backend_ncurses.cpp)
      target_compile_definitions(datapump_tui_adapter_test PRIVATE DATAPUMP_NCURSES_ADAPTER_TEST=1)
      target_include_directories(datapump_tui_adapter_test PRIVATE ${CURSES_INCLUDE_DIRS})
      target_link_libraries(datapump_tui_adapter_test PRIVATE datapump_terminal_ui ${CURSES_LIBRARIES})
      set_property(TARGET datapump_tui_adapter_test PROPERTY EXCLUDE_FROM_ALL TRUE)
      add_test(NAME tui_terminal COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_tui_terminal.py"
        --binary "$<TARGET_FILE:datapump_tui_adapter_test>")
      set_tests_properties(tui_terminal PROPERTIES LABELS "frontends" TIMEOUT 60)
    endif()
    if(DATAPUMP_TUI_BACKEND STREQUAL "winconsole")
      add_executable(test_winconsole tests/test_winconsole.cpp)
      target_link_libraries(test_winconsole PRIVATE datapump_terminal_ui)
      add_test(NAME tui_winconsole COMMAND test_winconsole)
      set_tests_properties(tui_winconsole PROPERTIES LABELS "frontends" TIMEOUT 60)
    endif()
  endif()
  if(DATAPUMP_BUILD_FB)
    add_test(NAME fb_self_check COMMAND datapump-fb --self-check)
    add_test(NAME fb_headless COMMAND datapump-fb --simulation --headless --frames 3)
    add_test(NAME fb_sdl COMMAND datapump-fb --simulation --frames 3)
    set_tests_properties(fb_sdl PROPERTIES ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_AUDIODRIVER=dummy")
    # The shared self-check performs CPU-heavy application checks (about 200s
    # under sanitizers on a busy host); it is not a presentation deadline.
    set_tests_properties(fb_self_check PROPERTIES LABELS "frontends" TIMEOUT 300)
    set_tests_properties(fb_headless fb_sdl PROPERTIES LABELS "frontends" TIMEOUT 30)
  endif()
endif()
