# Resolve SDK ELF dependencies without consulting the host's loader cache,
# RPATHs, or library directories. Used by the install-time portable packager.
include_guard(GLOBAL)

function(datapump_sdk_validate_path path root)
  file(REAL_PATH "${root}" root)
  get_filename_component(path "${path}" ABSOLUTE)
  cmake_path(NORMAL_PATH path)
  cmake_path(IS_PREFIX root "${path}" NORMALIZE inside)
  if(NOT inside)
    message(FATAL_ERROR "SDK path escapes its root: ${path}")
  endif()
  set(visited ${ARGN})
  list(LENGTH visited depth)
  if(depth GREATER 64)
    message(FATAL_ERROR "Excessive SDK symlink chain: ${path}")
  endif()
  file(RELATIVE_PATH relative "${root}" "${path}")
  string(REPLACE "/" ";" components "${relative}")
  set(current "${root}")
  foreach(component IN LISTS components)
    string(APPEND current "/${component}")
    if(IS_SYMLINK "${current}")
      if(current IN_LIST visited)
        message(FATAL_ERROR "Cyclic SDK symlink: ${current}")
      endif()
      file(READ_SYMLINK "${current}" following)
      if(NOT IS_ABSOLUTE "${following}")
        get_filename_component(parent "${current}" DIRECTORY)
        set(following "${parent}/${following}")
      endif()
      datapump_sdk_validate_path("${following}" "${root}" ${visited} "${current}")
    endif()
  endforeach()
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "SDK path is missing or has a broken symlink: ${path}")
  endif()
  file(REAL_PATH "${path}" real)
  cmake_path(IS_PREFIX root "${real}" NORMALIZE inside)
  if(NOT inside)
    message(FATAL_ERROR "SDK path escapes its root: ${path} -> ${real}")
  endif()
endfunction()

function(datapump_sdk_find_library name sysroot result)
  if(NOT name MATCHES "^[A-Za-z0-9_+.-]+$" OR name STREQUAL "." OR name STREQUAL "..")
    message(FATAL_ERROR "Invalid SDK dependency name: ${name}")
  endif()
  set(candidates "")
  foreach(directory lib lib64 usr/lib usr/lib64)
    if(IS_DIRECTORY "${sysroot}/${directory}")
      datapump_sdk_validate_path("${sysroot}/${directory}" "${sysroot}")
      file(GLOB_RECURSE matches LIST_DIRECTORIES FALSE "${sysroot}/${directory}/${name}")
      list(APPEND candidates ${matches})
    endif()
  endforeach()
  list(REMOVE_DUPLICATES candidates)
  list(SORT candidates)
  set(selected "")
  set(selected_digest "")
  foreach(candidate IN LISTS candidates)
    datapump_sdk_validate_path("${candidate}" "${sysroot}")
    file(SHA256 "${candidate}" digest)
    if(selected AND NOT digest STREQUAL selected_digest)
      message(FATAL_ERROR "Conflicting SDK libraries named ${name}: ${selected}; ${candidate}")
    endif()
    if(NOT selected)
      set(selected "${candidate}")
      set(selected_digest "${digest}")
    endif()
  endforeach()
  set(${result} "${selected}" PARENT_SCOPE)
endfunction()

function(datapump_sdk_runtime_dependencies result)
  cmake_parse_arguments(SDK "" "SYSROOT;OBJDUMP" "EXECUTABLES;LIBRARIES;EXCLUDE_REGEXES" ${ARGN})
  file(REAL_PATH "${SDK_SYSROOT}" sysroot)
  if(NOT IS_DIRECTORY "${sysroot}" OR NOT EXISTS "${SDK_OBJDUMP}")
    message(FATAL_ERROR "SDK runtime collection needs an existing sysroot and objdump")
  endif()
  set(queue ${SDK_EXECUTABLES} ${SDK_LIBRARIES})
  set(resolved ${SDK_LIBRARIES})
  foreach(library IN LISTS SDK_LIBRARIES)
    datapump_sdk_validate_path("${library}" "${sysroot}")
  endforeach()
  set(examined "")
  while(queue)
    list(POP_FRONT queue source)
    if(source IN_LIST examined)
      continue()
    endif()
    list(APPEND examined "${source}")
    execute_process(COMMAND "${SDK_OBJDUMP}" -p "${source}"
      RESULT_VARIABLE status OUTPUT_VARIABLE headers ERROR_VARIABLE error)
    if(NOT status STREQUAL "0")
      message(FATAL_ERROR "Cannot inspect SDK dependency ${source}: ${error}")
    endif()
    string(REGEX MATCHALL "\n[ \t]+NEEDED[ \t]+[^ \t\r\n]+" needed_entries "${headers}")
    foreach(entry IN LISTS needed_entries)
      string(REGEX REPLACE "^\n[ \t]+NEEDED[ \t]+" "" name "${entry}")
      set(excluded FALSE)
      foreach(pattern IN LISTS SDK_EXCLUDE_REGEXES)
        if(name MATCHES "${pattern}")
          set(excluded TRUE)
          break()
        endif()
      endforeach()
      if(excluded)
        continue()
      endif()
      datapump_sdk_find_library("${name}" "${sysroot}" dependency)
      if(NOT dependency)
        message(FATAL_ERROR "Missing SDK runtime dependency ${name}, needed by ${source}; host libraries are not searched")
      endif()
      list(APPEND resolved "${dependency}")
      list(APPEND queue "${dependency}")
    endforeach()
  endwhile()
  list(REMOVE_DUPLICATES resolved)
  set(${result} "${resolved}" PARENT_SCOPE)
endfunction()
